In [2]:
import pandas as pd
fresh = pd.read_csv("Freshmen.csv")
fresh

,Calculation1,Campus,City,County/State/ Territory,Fall Term,School,Sch Src FR,Uad Uc Ethn 6 Cat,adm (SUM),app (SUM),enr (SUM)
0,F BRAVO MEDICAL MAGNET HS51719,Riverside,Los Angeles,Los Angeles,2008,F BRAVO MEDICAL MAGNET HS,California Public High School,Hispanic/ Latino,39.0,50,10.0
1,ARAGON HIGH SCHOOL53163,Santa Barbara,San Mateo,San Mateo,2012,ARAGON HIGH SCHOOL,California Public High School,Asian,28.0,53,4.0
2,ETIWANDA HIGH SCHOOL50888,San Diego,Etiwanda,San Bernardino,2012,ETIWANDA HIGH SCHOOL,California Public High School,Asian,11.0,34,4.0
3,UPLAND HIGH SCHOOL53586,Merced,Upland,San Bernardino,2005,UPLAND HIGH SCHOOL,California Public High School,Asian,6.0,7,NaN
4,MORNINGSIDE HIGH SCHOOL51262,Los Angeles,Inglewood,Los Angeles,2006,MORNINGSIDE HIGH SCHOOL,California Public High School,All,5.0,22,NaN
5,SAN JOSE HIGH SCHOOL53098,Davis,San Jose,Santa Clara,2008,SAN JOSE HIGH SCHOOL,California Public High School,Asian,7.0,9,NaN
6,MIDDLE COLLEGE HIGH SCHOOL53204,Los Angeles,San Pablo,Contra Costa,2003,MIDDLE COLLEGE HIGH SCHOOL,California Public High School,Asian,4.0,6,NaN
7,BROOKWOOD HIGH SCHOOL112754,Universitywide,Snellville,Georgia,2016,BROOKWOOD HIGH SCHOOL,Non-CA Domestic High School,All,5.0,8,NaN
8,CHAFFEY HIGH SCHOOL52275,Universitywide,Ontario,San Bernardino,2011,CHAFFEY HIGH SCHOOL,California Public High School,Asian,6.0,8,3.0
9,VICTOR VALLEY HIGH SCHOOL53660,Universitywide,Victorville,San Bernardino,1999,VICTOR VALLEY HIGH SCHOOL,California Public High School,Asian,4.0,5,3.0
10,WINSTON CHURCHILL HIGH SCHOOL446273,Universitywide,San Antonio,Texas,2016,WINSTON CHURCHILL HIGH SCHOOL,Non-CA Domestic High School,All,3.0,12,NaN
11,LELAND HIGH SCHOOL53091,Universitywide,San Jose,Santa Clara,2003,LELAND HIGH SCHOOL,California Public High School,Asian,109.0,114,75.0
12,A B MILLER HIGH SCHOOL50944,Universitywide,Fontana,San Bernardino,2006,A B MILLER HIGH SCHOOL,California Public High School,Hispanic/ Latino,41.0,47,19.0
13,ESTANCIA HIGH SCHOOL50684,Universitywide,Costa Mesa,Orange,2009,ESTANCIA HIGH SCHOOL,California Public High School,Asian,7.0,7,3.0
14,WARREN HIGH SCHOOL50771,Universitywide,Downey,Los Angeles,1998,WARREN HIGH SCHOOL,California Public High School,All,45.0,53,26.0
15,AMITY REGIONAL HIGH SCHOOL70965,Universitywide,Woodbridge,Connecticut,1996,AMITY REGIONAL HIGH SCHOOL,Non-CA Domestic High School,All,NaN,5,NaN
16,ABRAHAM LINCOLN HIGH SCHOOL51520,Berkeley,Los Angeles,Los Angeles,2011,ABRAHAM LINCOLN HIGH SCHOOL,California Public High School,All,6.0,35,NaN
17,NEW TECHNOLOGY HIGH SCHOOL52102,Irvine,Napa,Napa,2005,NEW TECHNOLOGY HIGH SCHOOL,California Public High School,All,3.0,5,NaN
18,EL DORADO HIGH SCHOOL52478,Riverside,Placentia,Orange,2008,EL DORADO HIGH SCHOOL,California Public High School,Asian,17.0,18,5.0
19,BRAWLEY UNION HIGH SCHOOL50365,Universitywide,Brawley,Imperial,2000,BRAWLEY UNION HIGH SCHOOL,California Public High School,Hispanic/ Latino,11.0,14,4.0
20,A B MILLER HIGH SCHOOL50944,San Diego,Fontana,San Bernardino,2008,A B MILLER HIGH SCHOOL,California Public High School,Hispanic/ Latino,11.0,19,NaN
21,CHENGDU SHUDE HIGH SCHOOL694370,San Diego,NaN,"CHINA, PEOPLES REPUBLIC",2015,CHENGDU SHUDE HIGH SCHOOL,Foreign Institution,All,9.0,37,3.0
22,MORENO VALLEY HIGH SCHOOL53459,Riverside,Moreno Valley,Riverside,2016,MORENO VALLEY HIGH SCHOOL,California Public High School,All,54.0,100,31.0
23,F BRAVO MEDICAL MAGNET HS51719,Los Angeles,Los Angeles,Los Angeles,1998,F BRAVO MEDICAL MAGNET HS,California Public High School,African American,3.0,12,NaN
24,EDWARD C MERLO INSTITUTE54210,Universitywide,Stockton,San Joaquin,2016,EDWARD C MERLO INSTITUTE,California Public High School,All,NaN,5,NaN
25,ACADEMY OF THE CANYONS53262,Universitywide,Santa Clarita,Los Angeles,2013,ACADEMY OF THE CANYONS,California Public High School,White,7.0,15,4.0
26,ABRAHAM LINCOLN HIGH SCHOOL51520,Irvine,Los Angeles,Los Angeles,1999,ABRAHAM LINCOLN HIGH SCHOOL,California Public High School,Asian,NaN,43,NaN
27,CLOVIS EAST HIGH SCHOOL50622,Davis,Clovis,Fresno,2007,CLOVIS EAST HIGH SCHOOL,California Public High School,Asian,8.0,16,4.0
28,JEFFERSON HIGH SCHOOL50720,Universitywide,Daly City,San Mateo,2014,JEFFERSON HIGH SCHOOL,California Public High School,Asian,14.0,24,8.0
29,SAN JOSE HIGH SCHOOL53098,Merced,San Jose,Santa Clara,2013,SAN JOSE HIGH SCHOOL,California Public High School,Hispanic/ Latino,4.0,5,NaN
...,...,...,...,...,...,...,...,...,...,...,...
587471,ZHENHAI HIGH SCH OF ZHEJIANG694294,Universitywide,NaN,"CHINA, PEOPLES REPUBLIC",2015,ZHENHAI HIGH SCH OF ZHEJIANG,Foreign Institution,Inter- national,49.0,65,6.0
587472,ZHENHAI HIGH SCH OF ZHEJIANG694294,Universitywide,NaN,"CHINA, PEOPLES REPUBLIC",2016,ZHENHAI HIGH SCH OF ZHEJIANG,Foreign Institution,Inter- national,24.0,45,NaN
587473,ZHENHAI HIGH SCH OF ZHEJIANG694294,Universitywide,NaN,"CHINA, PEOPLES REPUBLIC",2017,ZHENHAI HIGH SCH OF ZHEJIANG,Foreign Institution,Inter- national,22.0,32,NaN
587474,ZHENHAI HIGH SCH OF ZHEJIANG694294,Berkeley,NaN,"CHINA, PEOPLES REPUBLIC",2013,ZHENHAI HIGH SCH OF ZHEJIANG,Foreign Institution,All,NaN,22,NaN
587475,ZHENHAI HIGH SCH OF ZHEJIANG694294,Berkeley,NaN,"CHINA, PEOPLES REPUBLIC",2013,ZHENHAI HIGH SCH OF ZHEJIANG,Foreign Institution,Inter- national,NaN,21,NaN
587476,ZHENHAI HIGH SCH OF ZHEJIANG694294,Davis,NaN,"CHINA, PEOPLES REPUBLIC",2013,ZHENHAI HIGH SCH OF ZHEJIANG,Foreign Institution,Inter- national,NaN,19,NaN
587477,ZHENHAI HIGH SCH OF ZHEJIANG694294,Davis,NaN,"CHINA, PEOPLES REPUBLIC",2017,ZHENHAI HIGH SCH OF ZHEJIANG,Foreign Institution,Inter- national,18.0,26,NaN
587478,ZHENHAI HIGH SCH OF ZHEJIANG694294,Irvine,NaN,"CHINA, PEOPLES REPUBLIC",2014,ZHENHAI HIGH SCH OF ZHEJIANG,Foreign Institution,All,8.0,25,NaN
587479,ZHENHAI HIGH SCH OF ZHEJIANG694294,Los Angeles,NaN,"CHINA, PEOPLES REPUBLIC",2012,ZHENHAI HIGH SCH OF ZHEJIANG,Foreign Institution,All,3.0,23,NaN
587480,ZHENHAI HIGH SCH OF ZHEJIANG694294,Los Angeles,NaN,"CHINA, PEOPLES REPUBLIC",2016,ZHENHAI HIGH SCH OF ZHEJIANG,Foreign Institution,Inter- national,NaN,29,NaN
587481,ZHENHAI HIGH SCH OF ZHEJIANG694294,San Diego,NaN,"CHINA, PEOPLES REPUBLIC",2013,ZHENHAI HIGH SCH OF ZHEJIANG,Foreign Institution,All,14.0,30,3.0
587482,ZHENHAI HIGH SCH OF ZHEJIANG694294,San Diego,NaN,"CHINA, PEOPLES REPUBLIC",2016,ZHENHAI HIGH SCH OF ZHEJIANG,Foreign Institution,All,9.0,40,NaN
587483,ZHENHAI HIGH SCH OF ZHEJIANG694294,San Diego,NaN,"CHINA, PEOPLES REPUBLIC",2015,ZHENHAI HIGH SCH OF ZHEJIANG,Foreign Institution,Inter- national,26.0,58,NaN
587484,ZHENHAI HIGH SCH OF ZHEJIANG694294,San Diego,NaN,"CHINA, PEOPLES REPUBLIC",2016,ZHENHAI HIGH SCH OF ZHEJIANG,Foreign Institution,Inter- national,NaN,39,NaN
587485,ZHUHAI NO 1 HIGH SCHOOL694565,Universitywide,NaN,"CHINA, PEOPLES REPUBLIC",2015,ZHUHAI NO 1 HIGH SCHOOL,Foreign Institution,All,21.0,27,14.0
587486,ZHUHAI NO 1 HIGH SCHOOL694565,Universitywide,NaN,"CHINA, PEOPLES REPUBLIC",2016,ZHUHAI NO 1 HIGH SCHOOL,Foreign Institution,All,18.0,21,10.0
587487,ZHUHAI NO 1 HIGH SCHOOL694565,Davis,NaN,"CHINA, PEOPLES REPUBLIC",2015,ZHUHAI NO 1 HIGH SCHOOL,Foreign Institution,All,3.0,10,NaN
587488,ZHUHAI NO 1 HIGH SCHOOL694565,Irvine,NaN,"CHINA, PEOPLES REPUBLIC",2015,ZHUHAI NO 1 HIGH SCHOOL,Foreign Institution,All,10.0,16,3.0
587489,ZHUHAI NO 1 HIGH SCHOOL694565,Irvine,NaN,"CHINA, PEOPLES REPUBLIC",2016,ZHUHAI NO 1 HIGH SCHOOL,Foreign Institution,All,15.0,17,NaN
587490,ZHUHAI NO 1 HIGH SCHOOL694565,Los Angeles,NaN,"CHINA, PEOPLES REPUBLIC",2015,ZHUHAI NO 1 HIGH SCHOOL,Foreign Institution,All,NaN,13,NaN
587491,ZHUHAI NO 1 HIGH SCHOOL694565,San Diego,NaN,"CHINA, PEOPLES REPUBLIC",2015,ZHUHAI NO 1 HIGH SCHOOL,Foreign Institution,All,11.0,19,5.0
587492,ZHUHAI NO 1 HIGH SCHOOL694565,San Diego,NaN,"CHINA, PEOPLES REPUBLIC",2016,ZHUHAI NO 1 HIGH SCHOOL,Foreign Institution,All,6.0,19,4.0
587493,ZIBO EXPERIMENTAL HIGH SCHOOL694601,Universitywide,NaN,"CHINA, PEOPLES REPUBLIC",2016,ZIBO EXPERIMENTAL HIGH SCHOOL,Foreign Institution,All,NaN,6,NaN
587494,ZIBO EXPERIMENTAL HIGH SCHOOL694601,Universitywide,NaN,"CHINA, PEOPLES REPUBLIC",2017,ZIBO EXPERIMENTAL HIGH SCHOOL,Foreign Institution,All,5.0,12,NaN
587495,ZURICH INTERNATIONAL SCHOOL796330,Universitywide,NaN,SWITZERLAND,2009,ZURICH INTERNATIONAL SCHOOL,Foreign Institution,All,4.0,6,NaN
587496,ZURICH INTERNATIONAL SCHOOL796330,Universitywide,NaN,SWITZERLAND,2012,ZURICH INTERNATIONAL SCHOOL,Foreign Institution,All,7.0,13,NaN
587497,ZURICH INTERNATIONAL SCHOOL796330,Universitywide,NaN,SWITZERLAND,2013,ZURICH INTERNATIONAL SCHOOL,Foreign Institution,All,8.0,14,NaN
587498,ZURICH INTERNATIONAL SCHOOL796330,Universitywide,NaN,SWITZERLAND,2017,ZURICH INTERNATIONAL SCHOOL,Foreign Institution,All,4.0,6,NaN
587499,ZURICH INTERNATIONAL SCHOOL796330,Los Angeles,NaN,SWITZERLAND,2017,ZURICH INTERNATIONAL SCHOOL,Foreign Institution,All,NaN,6,NaN
587500,ZURICH INTERNATIONAL SCHOOL796330,Santa Barbara,NaN,SWITZERLAND,2013,ZURICH INTERNATIONAL SCHOOL,Foreign Institution,All,4.0,8,NaN

In [3]:
gpa = pd.read_csv("GPA.csv")
gpa

,Calculation1,Campus,City,County/State/Country,Fall Term,Level,School,Adm GPA (SUM),App GPA (SUM),Enrl GPA (SUM)
0,GERMAN SWISS INTERNATIONAL SCH670905,Berkeley,NaN,HONG KONG,2012,Freshman,GERMAN SWISS INTERNATIONAL SCH,NaN,3.604000,NaN
1,AQUINAS HIGH SCHOOL052772,Riverside,San Bernardino,San Bernardino,1995,Freshman,AQUINAS HIGH SCHOOL,NaN,3.361429,NaN
2,DESIGN SCIENCE HIGH SCHOOL054003,Los Angeles,Fresno,Fresno,2012,Freshman,DESIGN SCIENCE HIGH SCHOOL,NaN,3.818000,NaN
3,BLOOMFIELD HILLS HIGH SCHOOL232447,Universitywide,Bloomfield Twp,Michigan,2015,Freshman,BLOOMFIELD HILLS HIGH SCHOOL,3.942000,3.950000,NaN
4,A B MILLER HIGH SCHOOL050944,Santa Barbara,Fontana,San Bernardino,1998,Freshman,A B MILLER HIGH SCHOOL,NaN,3.518571,NaN
5,WAYZATA HIGH SCHOOL242650,Davis,Plymouth,Minnesota,2013,Freshman,WAYZATA HIGH SCHOOL,NaN,3.660000,NaN
6,BISHOP MONTGOMERY HIGH SCHOOL053512,Merced,Torrance,Los Angeles,2012,Freshman,BISHOP MONTGOMERY HIGH SCHOOL,3.726000,3.561053,NaN
7,JOHN A ROWLAND HIGH SCHOOL052696,Santa Cruz,Rowland Heights,Los Angeles,1995,Freshman,JOHN A ROWLAND HIGH SCHOOL,3.346667,3.055385,NaN
8,JAMES A GARFIELD HIGH SCHOOL051635,Berkeley,Los Angeles,Los Angeles,2014,Freshman,JAMES A GARFIELD HIGH SCHOOL,4.118000,3.762895,4.055714
9,MONTEREY HIGH SCHOOL052050,Universitywide,Monterey,Monterey,2004,Freshman,MONTEREY HIGH SCHOOL,3.834565,3.714545,3.812759
10,CAJON HIGH SCHOOL052773,San Diego,San Bernardino,San Bernardino,2004,Freshman,CAJON HIGH SCHOOL,3.998571,3.543810,NaN
11,BENTONVILLE HIGH SCHOOL040175,Berkeley,Bentonville,Arkansas,2017,Freshman,BENTONVILLE HIGH SCHOOL,NaN,4.001250,NaN
12,ABRAHAM LINCOLN HIGH SCHOOL051520,Universitywide,Los Angeles,Los Angeles,2008,Freshman,ABRAHAM LINCOLN HIGH SCHOOL,3.566000,3.413882,3.609592
13,SACRAMENTO HIGH SCHOOL052735,Universitywide,Sacramento,Sacramento,2008,Freshman,SACRAMENTO HIGH SCHOOL,3.416607,3.250000,3.322759
14,AMADOR VALLEY HIGH SCHOOL052495,Santa Cruz,Pleasanton,Alameda,2003,Freshman,AMADOR VALLEY HIGH SCHOOL,3.582174,3.574400,3.415000
15,MARYSVILLE HIGH SCHOOL051925,Davis,Marysville,Yuba,2004,Freshman,MARYSVILLE HIGH SCHOOL,NaN,3.484545,NaN
16,ARNOLD O BECKMAN HIGH SCHOOL051267,Santa Cruz,Irvine,Orange,2007,Freshman,ARNOLD O BECKMAN HIGH SCHOOL,3.622917,3.501034,NaN
17,ACAD FOR CUL VIS TELE & PERF310451,San Diego,Hackensack,New Jersey,2014,Freshman,ACAD FOR CUL VIS TELE & PERF,NaN,3.844000,NaN
18,NOTRE DAME ACADEMY051730,Davis,Los Angeles,Los Angeles,2004,Freshman,NOTRE DAME ACADEMY,4.125556,3.808333,NaN
19,APPLE VALLEY HIGH SCHOOL050118,Riverside,Apple Valley,San Bernardino,2015,Freshman,APPLE VALLEY HIGH SCHOOL,3.815000,3.633939,3.551667
20,HANFORD HIGH SCHOOL051130,Santa Barbara,Hanford,Kings,1996,Freshman,HANFORD HIGH SCHOOL,NaN,3.198333,NaN
21,ALBUQUERQUE ACADEMY320003,Los Angeles,Albuquerque,New Mexico,2013,Freshman,ALBUQUERQUE ACADEMY,NaN,3.735714,NaN
22,SHELDON HIGH SCHOOL052792,Universitywide,Sacramento,Sacramento,2010,Freshman,SHELDON HIGH SCHOOL,3.775172,3.728154,3.878286
23,MONTGOMERY HIGH SCHOOL053328,Universitywide,Santa Rosa,Sonoma,1994,Freshman,MONTGOMERY HIGH SCHOOL,3.885075,3.830417,3.864054
24,CHANDLER HIGH SCHOOL030045,Berkeley,Chandler,Arizona,2015,Freshman,CHANDLER HIGH SCHOOL,NaN,4.114000,NaN
25,CRENSHAW HIGH SCHOOL051569,Santa Cruz,Los Angeles,Los Angeles,1998,Freshman,CRENSHAW HIGH SCHOOL,3.407143,3.112727,NaN
26,RANCHO COTATE HIGH SCHOOL052678,Santa Cruz,Rohnert Park,Sonoma,1999,Freshman,RANCHO COTATE HIGH SCHOOL,3.780000,3.584000,NaN
27,OAK PARK HIGH SCHOOL050006,Davis,Oak Park,Ventura,1997,Freshman,OAK PARK HIGH SCHOOL,3.920000,3.826429,NaN
28,ACADEMY OF OUR LADY OF GUAM525040,Universitywide,Hagatna,Guam,2017,Freshman,ACADEMY OF OUR LADY OF GUAM,NaN,3.863333,NaN
29,NOTRE DAME HIGH SCHOOL052748,Berkeley,Salinas,Monterey,1999,Freshman,NOTRE DAME HIGH SCHOOL,NaN,3.980000,NaN
...,...,...,...,...,...,...,...,...,...,...
333282,YUBA COLLEGE004994,Los Angeles,Marysville,Yuba,2011,Transfer,YUBA COLLEGE,NaN,3.365000,NaN
333283,YUBA COLLEGE004994,Universitywide,Marysville,Yuba,2011,Transfer,YUBA COLLEGE,3.508462,3.272444,3.492632
333284,YUBA COLLEGE004994,Santa Barbara,Marysville,Yuba,2012,Transfer,YUBA COLLEGE,NaN,3.153333,NaN
333285,YUBA COLLEGE004994,Los Angeles,Marysville,Yuba,2012,Transfer,YUBA COLLEGE,NaN,3.376000,NaN
333286,YUBA COLLEGE004994,Irvine,Marysville,Yuba,2012,Transfer,YUBA COLLEGE,NaN,3.172857,NaN
333287,YUBA COLLEGE004994,Davis,Marysville,Yuba,2012,Transfer,YUBA COLLEGE,3.460476,3.266486,3.453889
333288,YUBA COLLEGE004994,Universitywide,Marysville,Yuba,2012,Transfer,YUBA COLLEGE,3.467308,3.279250,3.486957
333289,YUBA COLLEGE004994,Santa Barbara,Marysville,Yuba,2013,Transfer,YUBA COLLEGE,3.560000,3.176000,NaN
333290,YUBA COLLEGE004994,Merced,Marysville,Yuba,2013,Transfer,YUBA COLLEGE,NaN,2.790000,NaN
333291,YUBA COLLEGE004994,Irvine,Marysville,Yuba,2013,Transfer,YUBA COLLEGE,NaN,3.104167,NaN
333292,YUBA COLLEGE004994,Davis,Marysville,Yuba,2013,Transfer,YUBA COLLEGE,3.486774,3.269362,3.522000
333293,YUBA COLLEGE004994,Universitywide,Marysville,Yuba,2013,Transfer,YUBA COLLEGE,3.489750,3.315714,3.518125
333294,YUBA COLLEGE004994,San Diego,Marysville,Yuba,2014,Transfer,YUBA COLLEGE,NaN,3.341429,NaN
333295,YUBA COLLEGE004994,Riverside,Marysville,Yuba,2014,Transfer,YUBA COLLEGE,3.370000,3.296000,NaN
333296,YUBA COLLEGE004994,Merced,Marysville,Yuba,2014,Transfer,YUBA COLLEGE,NaN,3.475000,NaN
333297,YUBA COLLEGE004994,Santa Barbara,Marysville,Yuba,2015,Transfer,YUBA COLLEGE,3.560000,3.321250,NaN
333298,YUBA COLLEGE004994,Riverside,Marysville,Yuba,2015,Transfer,YUBA COLLEGE,3.338000,3.338000,NaN
333299,YUBA COLLEGE004994,Merced,Marysville,Yuba,2015,Transfer,YUBA COLLEGE,NaN,3.034000,NaN
333300,YUBA COLLEGE004994,Los Angeles,Marysville,Yuba,2015,Transfer,YUBA COLLEGE,3.762000,3.490000,NaN
333301,YUBA COLLEGE004994,Irvine,Marysville,Yuba,2015,Transfer,YUBA COLLEGE,3.553333,3.344167,NaN
333302,YUBA COLLEGE004994,Berkeley,Marysville,Yuba,2015,Transfer,YUBA COLLEGE,NaN,3.564211,NaN
333303,YUBA COLLEGE004994,Santa Cruz,Marysville,Yuba,2016,Transfer,YUBA COLLEGE,3.355000,3.220000,NaN
333304,YUBA COLLEGE004994,Merced,Marysville,Yuba,2016,Transfer,YUBA COLLEGE,NaN,2.968182,NaN
333305,YUBA COLLEGE004994,Davis,Marysville,Yuba,2016,Transfer,YUBA COLLEGE,3.501515,3.356981,3.462692
333306,YUBA COLLEGE004994,Berkeley,Marysville,Yuba,2016,Transfer,YUBA COLLEGE,NaN,3.518400,NaN
333307,YUBA COLLEGE004994,Santa Barbara,Marysville,Yuba,2017,Transfer,YUBA COLLEGE,3.615000,3.456875,NaN
333308,YUBA COLLEGE004994,Riverside,Marysville,Yuba,2017,Transfer,YUBA COLLEGE,NaN,2.843750,NaN
333309,YUBA COLLEGE004994,Merced,Marysville,Yuba,2017,Transfer,YUBA COLLEGE,NaN,3.187500,NaN
333310,YUBA COLLEGE004994,Davis,Marysville,Yuba,2017,Transfer,YUBA COLLEGE,3.445000,3.343889,3.414583
333311,YUBA COLLEGE004994,Universitywide,Marysville,Yuba,2017,Transfer,YUBA COLLEGE,3.435870,3.343000,3.480857

In [4]:
trans = pd.read_csv("Transfers.csv")
trans

,Calculation1,Campus,City,County/State/ Territory,Fall Term,School,Sch Src TR,Uad Uc Ethn 6 Cat,adm (SUM),app (SUM),enr (SUM)
0,BUTTE COLLEGE4226,Davis,Oroville,Butte,2007,BUTTE COLLEGE,California Community Colleges (CCC),White,22.0,32,4.0
1,IMPERIAL VALLEY COLLEGE4358,Riverside,Imperial,Imperial,2008,IMPERIAL VALLEY COLLEGE,California Community Colleges (CCC),Hispanic/ Latino,13.0,27,3.0
2,ALLAN HANCOCK COLLEGE4002,Universitywide,Santa Maria,Santa Barbara,2012,ALLAN HANCOCK COLLEGE,California Community Colleges (CCC),White,97.0,133,65.0
3,AMERICAN RIVER COLLEGE4004,Berkeley,Sacramento,Sacramento,1996,AMERICAN RIVER COLLEGE,California Community Colleges (CCC),Hispanic/ Latino,8.0,14,6.0
4,CUESTA COLLEGE4101,Santa Barbara,San Luis Obispo,San Luis Obispo,2013,CUESTA COLLEGE,California Community Colleges (CCC),All,122.0,262,42.0
5,COLLEGE OF THE DESERT4085,Riverside,Palm Desert,Riverside,2015,COLLEGE OF THE DESERT,California Community Colleges (CCC),White,14.0,34,6.0
6,PASADENA CITY COLLEGE4604,Riverside,Pasadena,Los Angeles,1996,PASADENA CITY COLLEGE,California Community Colleges (CCC),White,28.0,34,NaN
7,GREEN RIVER COLLEGE4337,Los Angeles,Auburn,Washington,2012,GREEN RIVER COLLEGE,Non-California Institution (US),All,14.0,98,8.0
8,BUTTE COLLEGE4226,Santa Barbara,Oroville,Butte,2003,BUTTE COLLEGE,California Community Colleges (CCC),All,13.0,24,NaN
9,ALLAN HANCOCK COLLEGE4002,Universitywide,Santa Maria,Santa Barbara,2002,ALLAN HANCOCK COLLEGE,California Community Colleges (CCC),Hispanic/ Latino,50.0,69,32.0
10,NAPA VALLEY COLLEGE4530,Santa Cruz,Napa,Napa,2008,NAPA VALLEY COLLEGE,California Community Colleges (CCC),White,16.0,20,NaN
11,AMERICAN RIVER COLLEGE4004,Davis,Sacramento,Sacramento,2010,AMERICAN RIVER COLLEGE,California Community Colleges (CCC),Asian,82.0,124,52.0
12,MIRACOSTA COLLEGE4582,Universitywide,Oceanside,San Diego,1997,MIRACOSTA COLLEGE,California Community Colleges (CCC),Inter- national,8.0,10,6.0
13,CITRUS COLLEGE4051,Universitywide,Glendora,Los Angeles,2008,CITRUS COLLEGE,California Community Colleges (CCC),Hispanic/ Latino,40.0,55,31.0
14,CHAFFEY COLLEGE4046,Berkeley,Rnch Cmnga,San Bernardino,2000,CHAFFEY COLLEGE,California Community Colleges (CCC),Asian,NaN,16,NaN
15,CANADA COLLEGE4109,Universitywide,Redwood City,San Mateo,2000,CANADA COLLEGE,California Community Colleges (CCC),Hispanic/ Latino,9.0,13,NaN
16,ANTELOPE VALLEY COLLEGE4005,Santa Barbara,Lancaster,Los Angeles,2004,ANTELOPE VALLEY COLLEGE,California Community Colleges (CCC),Hispanic/ Latino,21.0,32,NaN
17,ALLAN HANCOCK COLLEGE4002,Universitywide,Santa Maria,Santa Barbara,1994,ALLAN HANCOCK COLLEGE,California Community Colleges (CCC),All,72.0,100,46.0
18,SIERRA COLLEGE4697,Santa Cruz,Rocklin,Placer,1999,SIERRA COLLEGE,California Community Colleges (CCC),White,32.0,58,NaN
19,ALLAN HANCOCK COLLEGE4002,Universitywide,Santa Maria,Santa Barbara,1995,ALLAN HANCOCK COLLEGE,California Community Colleges (CCC),Hispanic/ Latino,30.0,34,24.0
20,PASADENA CITY COLLEGE4604,Los Angeles,Pasadena,Los Angeles,2000,PASADENA CITY COLLEGE,California Community Colleges (CCC),Hispanic/ Latino,71.0,137,47.0
21,DIABLO VALLEY COLLEGE4295,San Diego,Pleasant Hill,Contra Costa,2017,DIABLO VALLEY COLLEGE,California Community Colleges (CCC),African American,34.0,44,12.0
22,PALOMAR COLLEGE4602,Riverside,San Marcos,San Diego,2013,PALOMAR COLLEGE,California Community Colleges (CCC),Hispanic/ Latino,38.0,42,8.0
23,SAN DIEGO MESA COLLEGE4735,San Diego,San Diego,San Diego,2001,SAN DIEGO MESA COLLEGE,California Community Colleges (CCC),Inter- national,15.0,21,11.0
24,CHABOT COLLEGE4725,Berkeley,Hayward,Alameda,2017,CHABOT COLLEGE,California Community Colleges (CCC),Hispanic/ Latino,30.0,92,26.0
25,BARSTOW COLLEGE4020,Los Angeles,Barstow,San Bernardino,2005,BARSTOW COLLEGE,California Community Colleges (CCC),All,NaN,12,NaN
26,UC BERKELEY4833,Universitywide,Berkeley,Alameda,2009,UC BERKELEY,University of California (UC),All,75.0,103,35.0
27,EL CAMINO COLLEGE4302,Davis,Torrance,Los Angeles,1999,EL CAMINO COLLEGE,California Community Colleges (CCC),Hispanic/ Latino,NaN,12,NaN
28,COLLEGE OF THE CANYONS4117,Berkeley,Santa Clarita,Los Angeles,2005,COLLEGE OF THE CANYONS,California Community Colleges (CCC),Domestic Unknown,5.0,18,NaN
29,GLENDALE COMMUNITY COLLEGE4327,Santa Cruz,Glendale,Los Angeles,2011,GLENDALE COMMUNITY COLLEGE,California Community Colleges (CCC),White,76.0,112,6.0
...,...,...,...,...,...,...,...,...,...,...,...
103935,WHATCOM CMTY COLLEGE1275,Berkeley,Bellingham,Washington,2017,WHATCOM CMTY COLLEGE,Non-California Institution (US),Inter- national,NaN,22,NaN
103936,WHATCOM CMTY COLLEGE1275,Davis,Bellingham,Washington,2017,WHATCOM CMTY COLLEGE,Non-California Institution (US),Inter- national,6.0,18,NaN
103937,WHATCOM CMTY COLLEGE1275,Irvine,Bellingham,Washington,2017,WHATCOM CMTY COLLEGE,Non-California Institution (US),Inter- national,6.0,22,NaN
103938,WHATCOM CMTY COLLEGE1275,Los Angeles,Bellingham,Washington,2013,WHATCOM CMTY COLLEGE,Non-California Institution (US),All,NaN,10,NaN
103939,WHATCOM CMTY COLLEGE1275,Los Angeles,Bellingham,Washington,2015,WHATCOM CMTY COLLEGE,Non-California Institution (US),All,NaN,14,NaN
103940,WHATCOM CMTY COLLEGE1275,Los Angeles,Bellingham,Washington,2016,WHATCOM CMTY COLLEGE,Non-California Institution (US),All,6.0,18,NaN
103941,WHATCOM CMTY COLLEGE1275,Los Angeles,Bellingham,Washington,2017,WHATCOM CMTY COLLEGE,Non-California Institution (US),All,NaN,44,NaN
103942,WHATCOM CMTY COLLEGE1275,Los Angeles,Bellingham,Washington,2015,WHATCOM CMTY COLLEGE,Non-California Institution (US),Inter- national,NaN,12,NaN
103943,WHATCOM CMTY COLLEGE1275,San Diego,Bellingham,Washington,2016,WHATCOM CMTY COLLEGE,Non-California Institution (US),All,8.0,10,NaN
103944,WHATCOM CMTY COLLEGE1275,San Diego,Bellingham,Washington,2017,WHATCOM CMTY COLLEGE,Non-California Institution (US),Inter- national,6.0,24,NaN
103945,WHATCOM CMTY COLLEGE1275,Santa Cruz,Bellingham,Washington,2017,WHATCOM CMTY COLLEGE,Non-California Institution (US),All,10.0,16,NaN
103946,WHATCOM CMTY COLLEGE1275,Santa Cruz,Bellingham,Washington,2017,WHATCOM CMTY COLLEGE,Non-California Institution (US),Inter- national,NaN,14,NaN
103947,WHITMAN COLLEGE4951,Universitywide,Walla Walla,Washington,2016,WHITMAN COLLEGE,Non-California Institution (US),All,8.0,14,NaN
103948,WHITMAN COLLEGE4951,Davis,Walla Walla,Washington,2016,WHITMAN COLLEGE,Non-California Institution (US),All,6.0,10,NaN
103949,WILLAMETTE UNIVERSITY4954,Universitywide,Salem,Oregon,1998,WILLAMETTE UNIVERSITY,Non-California Institution (US),All,NaN,10,NaN
103950,WILLAMETTE UNIVERSITY4954,Universitywide,Salem,Oregon,1999,WILLAMETTE UNIVERSITY,Non-California Institution (US),All,NaN,10,NaN
103951,WILLAMETTE UNIVERSITY4954,Universitywide,Salem,Oregon,2000,WILLAMETTE UNIVERSITY,Non-California Institution (US),All,7.0,17,NaN
103952,WILLAMETTE UNIVERSITY4954,Universitywide,Salem,Oregon,2001,WILLAMETTE UNIVERSITY,Non-California Institution (US),All,3.0,6,3.0
103953,WILLAMETTE UNIVERSITY4954,Universitywide,Salem,Oregon,2017,WILLAMETTE UNIVERSITY,Non-California Institution (US),All,10.0,10,NaN
103954,WILLAMETTE UNIVERSITY4954,Universitywide,Salem,Oregon,2000,WILLAMETTE UNIVERSITY,Non-California Institution (US),White,3.0,13,NaN
103955,WILLAMETTE UNIVERSITY4954,Davis,Salem,Oregon,2016,WILLAMETTE UNIVERSITY,Non-California Institution (US),All,NaN,10,NaN
103956,WILLIAM R HARPER COLLEGE1932,Universitywide,Palatine,Illinois,2001,WILLIAM R HARPER COLLEGE,Non-California Institution (US),All,NaN,16,NaN
103957,WILLIAM R HARPER COLLEGE1932,Universitywide,Palatine,Illinois,2005,WILLIAM R HARPER COLLEGE,Non-California Institution (US),All,NaN,14,NaN
103958,WISCONSIN990328,Universitywide,NaN,Wisconsin,2005,WISCONSIN,Non-California Institution (US),All,NaN,14,NaN
103959,WISCONSIN990328,Universitywide,NaN,Wisconsin,2015,WISCONSIN,Non-California Institution (US),All,NaN,5,NaN
103960,WISCONSIN990328,Universitywide,NaN,Wisconsin,2016,WISCONSIN,Non-California Institution (US),All,NaN,12,NaN
103961,WRIGHT STATE UNIVERSITY DAYTN1179,Universitywide,Dayton,Ohio,2013,WRIGHT STATE UNIVERSITY DAYTN,Non-California Institution (US),All,NaN,12,NaN
103962,YAVAPAI COLLEGE4996,Universitywide,Prescott,Arizona,2009,YAVAPAI COLLEGE,Non-California Institution (US),All,12.0,13,3.0
103963,CALIF MARITIME ACADEMY4035,Universitywide,Vallejo,Solano,2007,CALIF MARITIME ACADEMY,Other (not to include unknown),All,8.0,12,8.0
103964,COPPER MOUNTAIN COLL3889,Riverside,Joshua Tree,San Bernardino,2004,COPPER MOUNTAIN COLL,Other (not to include unknown),All,10.0,12,6.0

In [35]:
#How is the ratio of admitted students to applied students differ amongst different ethnicities at UC Berkeley Over various Semesters?
#--Data Frames only cover Fall 2017--

In [6]:
trans = trans.rename(columns = {'adm (SUM)':'admitted', 'app (SUM)':'applied', 'enr (SUM)':'enrolled', 'Uad Uc Ethn 6 Cat':'Ethnicity'})

In [7]:
fresh = fresh.rename(columns = {'adm (SUM)':'admitted', 'app (SUM)':'applied', 'enr (SUM)':'enrolled', 'Uad Uc Ethn 6 Cat':'Ethnicity'})

In [8]:
gpa = gpa.rename(columns = {'adm (SUM)':'admitted_gpa', 'app (SUM)':'applied_gpa', 'enr (SUM)':'enrolled_gpa'})

In [29]:
trans_2017 = trans[trans["Fall Term"] == 2017]

In [26]:
fresh_2017 = fresh[fresh["Fall Term"] == 2017]

In [30]:
fresh_2017

,Calculation1,Campus,City,County/State/ Territory,Fall Term,School,Sch Src FR,Ethnicity,admitted,applied,enrolled
32,LANCASTER HIGH SCHOOL51412,Berkeley,Lancaster,Los Angeles,2017,LANCASTER HIGH SCHOOL,California Public High School,All,NaN,18,NaN
51,POINT LOMA HIGH SCHOOL52870,Irvine,San Diego,San Diego,2017,POINT LOMA HIGH SCHOOL,California Public High School,White,11.0,31,NaN
64,FLOYD B BUCHANAN HIGH SCHOOL50618,Merced,Clovis,Fresno,2017,FLOYD B BUCHANAN HIGH SCHOOL,California Public High School,White,5.0,5,NaN
77,CLOVIS WEST HIGH SCHOOL50982,Universitywide,Fresno,Fresno,2017,CLOVIS WEST HIGH SCHOOL,California Public High School,Asian,16.0,27,11.0
85,CENTENNIAL HIGH SCHOOL50650,Irvine,Compton,Los Angeles,2017,CENTENNIAL HIGH SCHOOL,California Public High School,All,5.0,34,3.0
113,BENICIA HIGH SCHOOL50280,Santa Cruz,Benicia,Solano,2017,BENICIA HIGH SCHOOL,California Public High School,Asian,4.0,8,NaN
131,ACADEMY OF SCIENTIFIC EXPLORAT54563,Merced,San Fernando,Los Angeles,2017,ACADEMY OF SCIENTIFIC EXPLORAT,California Public High School,All,11.0,13,NaN
138,ALLIANCE COLLINS FAMILY COLRDY54118,Davis,Huntington Park,Los Angeles,2017,ALLIANCE COLLINS FAMILY COLRDY,California Public High School,All,7.0,28,3.0
158,RIVERSIDE STEM ACADEMY54784,Irvine,Riverside,Riverside,2017,RIVERSIDE STEM ACADEMY,California Public High School,Hispanic/ Latino,NaN,8,NaN
164,SONOMA VALLEY HIGH SCHOOL53390,Davis,Sonoma,Sonoma,2017,SONOMA VALLEY HIGH SCHOOL,California Public High School,Asian,NaN,7,NaN
185,DUBLIN HIGH SCHOOL50784,Santa Barbara,Dublin,Alameda,2017,DUBLIN HIGH SCHOOL,California Public High School,All,50.0,147,7.0
196,HARMONY MAGNET ACADEMY54414,Merced,Porterville,Tulare,2017,HARMONY MAGNET ACADEMY,California Public High School,All,9.0,11,NaN
201,THOMAS SPRIGG WOOTTON HS210909,Universitywide,Rockville,Maryland,2017,THOMAS SPRIGG WOOTTON HS,Non-CA Domestic High School,All,28.0,54,3.0
202,ARROYO HIGH SCHOOL53125,San Diego,San Lorenzo,Alameda,2017,ARROYO HIGH SCHOOL,California Public High School,Asian,12.0,34,NaN
205,TROY HIGH SCHOOL51009,Irvine,Fullerton,Orange,2017,TROY HIGH SCHOOL,California Public High School,Domestic Unknown,NaN,12,NaN
213,LAKE OSWEGO HIGH SCHOOL380795,Universitywide,Lake Oswego,Oregon,2017,LAKE OSWEGO HIGH SCHOOL,Non-CA Domestic High School,All,12.0,21,6.0
228,ALLIANCE PIERA BARBAGLIA HSA54361,Riverside,Los Angeles,Los Angeles,2017,ALLIANCE PIERA BARBAGLIA HSA,California Public High School,All,5.0,19,NaN
252,ARROYO HIGH SCHOOL50830,Los Angeles,El Monte,Los Angeles,2017,ARROYO HIGH SCHOOL,California Public High School,All,14.0,98,8.0
275,EL CAMINO REAL CHARTER HIGH SC53801,Irvine,Woodland Hills,Los Angeles,2017,EL CAMINO REAL CHARTER HIGH SC,California Public High School,African American,NaN,12,NaN
305,ESPERANZA HIGH SCHOOL50093,Irvine,Anaheim,Orange,2017,ESPERANZA HIGH SCHOOL,California Public High School,White,9.0,19,NaN
325,GOLDEN VALLEY HIGH SCHOOL51953,Universitywide,Merced,Merced,2017,GOLDEN VALLEY HIGH SCHOOL,California Public High School,Hispanic/ Latino,29.0,36,18.0
328,SIERRA CANYON SCHOOL54038,Santa Barbara,Chatsworth,Los Angeles,2017,SIERRA CANYON SCHOOL,California Private High School,White,NaN,13,NaN
334,ROSAMOND HIGH SCHOOL52684,Santa Barbara,Rosamond,Kern,2017,ROSAMOND HIGH SCHOOL,California Public High School,Hispanic/ Latino,4.0,9,NaN
356,TAIWAN990011,Los Angeles,NaN,TAIWAN,2017,TAIWAN,Foreign Institution,All,7.0,83,NaN
357,DESERT CHRISTIAN HIGH SCHOOL51389,Universitywide,Lancaster,Los Angeles,2017,DESERT CHRISTIAN HIGH SCHOOL,California Private High School,Inter- national,6.0,10,4.0
391,ACADEMY SCIENCE & ENGINEERING54626,Berkeley,Los Angeles,Los Angeles,2017,ACADEMY SCIENCE & ENGINEERING,California Public High School,All,NaN,10,NaN
392,PALM DESERT HIGH SCHOOL52319,San Diego,Palm Desert,Riverside,2017,PALM DESERT HIGH SCHOOL,California Public High School,White,5.0,27,NaN
405,LA CANADA HIGH SCHOOL51312,San Diego,La Canada,Los Angeles,2017,LA CANADA HIGH SCHOOL,California Public High School,All,48.0,141,NaN
442,ROBERT A MILLIKAN HIGH SCHOOL51476,Universitywide,Long Beach,Los Angeles,2017,ROBERT A MILLIKAN HIGH SCHOOL,California Public High School,All,99.0,164,35.0
449,ASPIRE OLLIN UNIV PREP ACDMY54735,Santa Barbara,Huntington Park,Los Angeles,2017,ASPIRE OLLIN UNIV PREP ACDMY,California Public High School,All,4.0,37,3.0
...,...,...,...,...,...,...,...,...,...,...,...
587320,YONGSAN INTL SCHOOL SEOUL682230,Berkeley,NaN,"KOREA, REPUBLIC OF (SOUTH)",2017,YONGSAN INTL SCHOOL SEOUL,Foreign Institution,Inter- national,NaN,6,NaN
587325,YONGSAN INTL SCHOOL SEOUL682230,Irvine,NaN,"KOREA, REPUBLIC OF (SOUTH)",2017,YONGSAN INTL SCHOOL SEOUL,Foreign Institution,All,18.0,28,NaN
587328,YONGSAN INTL SCHOOL SEOUL682230,Irvine,NaN,"KOREA, REPUBLIC OF (SOUTH)",2017,YONGSAN INTL SCHOOL SEOUL,Foreign Institution,Asian,12.0,16,NaN
587332,YONGSAN INTL SCHOOL SEOUL682230,Irvine,NaN,"KOREA, REPUBLIC OF (SOUTH)",2017,YONGSAN INTL SCHOOL SEOUL,Foreign Institution,Inter- national,5.0,10,NaN
587336,YONGSAN INTL SCHOOL SEOUL682230,Los Angeles,NaN,"KOREA, REPUBLIC OF (SOUTH)",2017,YONGSAN INTL SCHOOL SEOUL,Foreign Institution,All,7.0,31,NaN
587339,YONGSAN INTL SCHOOL SEOUL682230,Los Angeles,NaN,"KOREA, REPUBLIC OF (SOUTH)",2017,YONGSAN INTL SCHOOL SEOUL,Foreign Institution,Asian,NaN,20,NaN
587343,YONGSAN INTL SCHOOL SEOUL682230,Los Angeles,NaN,"KOREA, REPUBLIC OF (SOUTH)",2017,YONGSAN INTL SCHOOL SEOUL,Foreign Institution,Inter- national,NaN,9,NaN
587344,YONGSAN INTL SCHOOL SEOUL682230,San Diego,NaN,"KOREA, REPUBLIC OF (SOUTH)",2017,YONGSAN INTL SCHOOL SEOUL,Foreign Institution,All,16.0,31,NaN
587346,YONGSAN INTL SCHOOL SEOUL682230,San Diego,NaN,"KOREA, REPUBLIC OF (SOUTH)",2017,YONGSAN INTL SCHOOL SEOUL,Foreign Institution,Inter- national,NaN,9,NaN
587350,YORK HOUSE SCHOOL821630,Universitywide,NaN,CANADA,2017,YORK HOUSE SCHOOL,Foreign Institution,All,9.0,13,3.0
587364,YUEZHOU HIGH SCHOOL694441,Universitywide,NaN,"CHINA, PEOPLES REPUBLIC",2017,YUEZHOU HIGH SCHOOL,Foreign Institution,All,5.0,8,NaN
587379,ZHANGJIAGANG IVY EXPERIMENTAL694355,Davis,NaN,"CHINA, PEOPLES REPUBLIC",2017,ZHANGJIAGANG IVY EXPERIMENTAL,Foreign Institution,All,23.0,28,3.0
587383,ZHANGJIAGANG IVY EXPERIMENTAL694355,San Diego,NaN,"CHINA, PEOPLES REPUBLIC",2017,ZHANGJIAGANG IVY EXPERIMENTAL,Foreign Institution,All,17.0,29,NaN
587390,ZHEJIANG FUYANG HIGH SCHOOL694371,Universitywide,NaN,"CHINA, PEOPLES REPUBLIC",2017,ZHEJIANG FUYANG HIGH SCHOOL,Foreign Institution,All,11.0,18,4.0
587403,ZHEJIANG HUZHOU HIGH SCHOOL694499,Universitywide,NaN,"CHINA, PEOPLES REPUBLIC",2017,ZHEJIANG HUZHOU HIGH SCHOOL,Foreign Institution,All,10.0,13,8.0
587405,ZHEJIANG HUZHOU HIGH SCHOOL694499,Irvine,NaN,"CHINA, PEOPLES REPUBLIC",2017,ZHEJIANG HUZHOU HIGH SCHOOL,Foreign Institution,All,7.0,8,NaN
587417,ZHENGZHOU FOREIGN LANGUAGE SCH694361,Davis,NaN,"CHINA, PEOPLES REPUBLIC",2017,ZHENGZHOU FOREIGN LANGUAGE SCH,Foreign Institution,All,29.0,43,4.0
587425,ZHENGZHOU FOREIGN LANGUAGE SCH694361,Los Angeles,NaN,"CHINA, PEOPLES REPUBLIC",2017,ZHENGZHOU FOREIGN LANGUAGE SCH,Foreign Institution,All,5.0,56,NaN
587435,ZHENGZHOU FOREIGN LANGUAGE SCH694361,Santa Barbara,NaN,"CHINA, PEOPLES REPUBLIC",2017,ZHENGZHOU FOREIGN LANGUAGE SCH,Foreign Institution,All,30.0,63,3.0
587439,ZHENGZHOU MIDDLE SCHOOL694448,Universitywide,NaN,"CHINA, PEOPLES REPUBLIC",2017,ZHENGZHOU MIDDLE SCHOOL,Foreign Institution,All,7.0,12,5.0
587442,ZHENGZHOU MIDDLE SCHOOL694448,Santa Cruz,NaN,"CHINA, PEOPLES REPUBLIC",2017,ZHENGZHOU MIDDLE SCHOOL,Foreign Institution,All,3.0,5,NaN
587448,ZHENGZHOU NO 7 MIDDLE SCHOOL694440,Universitywide,NaN,"CHINA, PEOPLES REPUBLIC",2017,ZHENGZHOU NO 7 MIDDLE SCHOOL,Foreign Institution,All,28.0,33,6.0
587456,ZHENGZHOU NO 7 MIDDLE SCHOOL694440,San Diego,NaN,"CHINA, PEOPLES REPUBLIC",2017,ZHENGZHOU NO 7 MIDDLE SCHOOL,Foreign Institution,All,13.0,25,NaN
587457,ZHENGZHOU NO 7 MIDDLE SCHOOL694440,Santa Barbara,NaN,"CHINA, PEOPLES REPUBLIC",2017,ZHENGZHOU NO 7 MIDDLE SCHOOL,Foreign Institution,All,12.0,20,NaN
587465,ZHENGZHOU NO 47 MIDDLE & HIGH694388,Davis,NaN,"CHINA, PEOPLES REPUBLIC",2017,ZHENGZHOU NO 47 MIDDLE & HIGH,Foreign Institution,All,4.0,6,NaN
587473,ZHENHAI HIGH SCH OF ZHEJIANG694294,Universitywide,NaN,"CHINA, PEOPLES REPUBLIC",2017,ZHENHAI HIGH SCH OF ZHEJIANG,Foreign Institution,Inter- national,22.0,32,NaN
587477,ZHENHAI HIGH SCH OF ZHEJIANG694294,Davis,NaN,"CHINA, PEOPLES REPUBLIC",2017,ZHENHAI HIGH SCH OF ZHEJIANG,Foreign Institution,Inter- national,18.0,26,NaN
587494,ZIBO EXPERIMENTAL HIGH SCHOOL694601,Universitywide,NaN,"CHINA, PEOPLES REPUBLIC",2017,ZIBO EXPERIMENTAL HIGH SCHOOL,Foreign Institution,All,5.0,12,NaN
587498,ZURICH INTERNATIONAL SCHOOL796330,Universitywide,NaN,SWITZERLAND,2017,ZURICH INTERNATIONAL SCHOOL,Foreign Institution,All,4.0,6,NaN
587499,ZURICH INTERNATIONAL SCHOOL796330,Los Angeles,NaN,SWITZERLAND,2017,ZURICH INTERNATIONAL SCHOOL,Foreign Institution,All,NaN,6,NaN

In [37]:
#number of freshmen that applied to each campus based on ethnicity in Fall 2017
fresh_applied_by_campus = fresh_2017.groupby(['Campus','Ethnicity']).applied.agg(['sum'])
fresh_applied_by_campus #.drop(index='All', level=1)

                                    sum
Campus         Ethnicity
Berkeley       African American    1395
               All                58412
               American Indian        5
               Asian              19813
               Domestic Unknown     675
               Hispanic/ Latino   10343
               Inter- national     3791
               White              12562
Davis          African American    1214
               All                52849
               Asian              17194
               Domestic Unknown     504
               Hispanic/ Latino   12092
               Inter- national     2536
               White              10356
Irvine         African American    1647
               All                63178
               Asian              22302
               Domestic Unknown     434
               Hispanic/ Latino   19409
               Inter- national     2993
               White               8186
Los Angeles    African American    2366
               All                72518
               Asian              22422
               Domestic Unknown     676
               Hispanic/ Latino   17701
               Inter- national     4542
               White              14583
Merced         African American     419
...                                 ...
San Diego      African American    1655
               All                62159
               Asian              21348
               Domestic Unknown     584
               Hispanic/ Latino   14284
               Inter- national     4040
               White              11371
Santa Barbara  African American    1411
               All                58857
               American Indian        6
               Asian              16569
               Domestic Unknown     563
               Hispanic/ Latino   15051
               Inter- national     2465
               White              14358
Santa Cruz     African American     793
               All                36122
               Asian              10514
               Domestic Unknown     249
               Hispanic/ Latino   10132
               Inter- national      871
               White               8472
Universitywide African American    5422
               All               146228
               American Indian       31
               Asian              37641
               Domestic Unknown    1150
               Hispanic/ Latino   40677
               Inter- national     9664
               White              30921

[73 rows x 1 columns]

In [ ]:
#number of freshmen admitted to each campus based on ethnicity in Fall 2017
fresh_admitted_by_campus = fresh_2017.groupby(['Campus','Ethnicity']).admitted.agg(['sum'])
fresh_admitted_by_campus

In [36]:
#number of transfer students that applied to each campus organised by ethnicity in Fall 2017
trans_applied_by_campus = trans_2017.groupby(['Campus','Ethnicity']).applied.agg(['sum'])
trans_applied_by_campus #.drop(index='All', level=1)

                                   sum
Campus         Ethnicity
Berkeley       African American   1502
               All               33796
               American Indian      20
               Asian              8728
               Domestic Unknown    166
               Hispanic/ Latino   7162
               Inter- national    5584
               White              8756
Davis          African American   1278
               All               31850
               American Indian      38
               Asian              8944
               Domestic Unknown    244
               Hispanic/ Latino   6620
               Inter- national    5024
               White              7582
Irvine         African American   1308
               All               36820
               American Indian      22
               Asian             11348
               Domestic Unknown    210
               Hispanic/ Latino   8220
               Inter- national    5902
               White              7984
Los Angeles    African American   1862
               All               39978
               American Indian      52
               Asian             10240
               Domestic Unknown    406
               Hispanic/ Latino   9236
...                                ...
San Diego      American Indian      26
               Asian              9154
               Domestic Unknown    186
               Hispanic/ Latino   6632
               Inter- national    6056
               White              8046
Santa Barbara  African American   1150
               All               31498
               American Indian      36
               Asian              7604
               Domestic Unknown    186
               Hispanic/ Latino   7308
               Inter- national    4872
               White              8604
Santa Cruz     African American    696
               All               18856
               American Indian      28
               Asian              4608
               Domestic Unknown    110
               Hispanic/ Latino   4962
               Inter- national    1628
               White              5414
Universitywide African American   3562
               All               72922
               American Indian     232
               Asian             17768
               Domestic Unknown   1052
               Hispanic/ Latino  18152
               Inter- national    9390
               White             19506

[78 rows x 1 columns]

In [33]:
#number of transfer students admitted to each campus, organised by ethnicity in Fall 2017
trans_admitted_by_campus = trans_2017.groupby(['Campus','Ethnicity']).admitted.agg(['sum'])
trans_admitted_by_campus #.drop(index='All', level=1)

                                     sum
Campus         Ethnicity
Berkeley       African American    266.0
               All                8390.0
               American Indian       0.0
               Asian              2092.0
               Domestic Unknown     14.0
               Hispanic/ Latino   1626.0
               Inter- national    1186.0
               White              2476.0
Davis          African American    628.0
               All               19978.0
               American Indian      22.0
               Asian              5634.0
               Domestic Unknown    140.0
               Hispanic/ Latino   3940.0
               Inter- national    3448.0
               White              4952.0
Irvine         African American    556.0
               All               20256.0
               American Indian       6.0
               Asian              6258.0
               Domestic Unknown     84.0
               Hispanic/ Latino   4352.0
               Inter- national    3092.0
               White              4732.0
Los Angeles    African American    442.0
               All               10816.0
               American Indian       0.0
               Asian              2660.0
               Domestic Unknown     36.0
               Hispanic/ Latino   2314.0
...                                  ...
San Diego      American Indian      12.0
               Asian              5480.0
               Domestic Unknown    112.0
               Hispanic/ Latino   3628.0
               Inter- national    2842.0
               White              5054.0
Santa Barbara  African American    550.0
               All               18202.0
               American Indian      28.0
               Asian              4164.0
               Domestic Unknown    106.0
               Hispanic/ Latino   3956.0
               Inter- national    3116.0
               White              5300.0
Santa Cruz     African American    326.0
               All               11588.0
               American Indian      14.0
               Asian              2686.0
               Domestic Unknown     76.0
               Hispanic/ Latino   3032.0
               Inter- national     962.0
               White              3550.0
Universitywide African American   2270.0
               All               52366.0
               American Indian     140.0
               Asian             13236.0
               Domestic Unknown    634.0
               Hispanic/ Latino  12986.0
               Inter- national    6920.0
               White             14188.0

[78 rows x 1 columns]