In [1]:
from __future__ import print_function, division
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
gpa = pd.read_csv("GPA.csv")

In [3]:
gpa.head()

,Calculation1,Campus,City,County/State/Country,Fall Term,Level,School,Adm GPA (SUM),App GPA (SUM),Enrl GPA (SUM)
0,GERMAN SWISS INTERNATIONAL SCH670905,Berkeley,NaN,HONG KONG,2012,Freshman,GERMAN SWISS INTERNATIONAL SCH,NaN,3.604000,NaN
1,AQUINAS HIGH SCHOOL052772,Riverside,San Bernardino,San Bernardino,1995,Freshman,AQUINAS HIGH SCHOOL,NaN,3.361429,NaN
2,DESIGN SCIENCE HIGH SCHOOL054003,Los Angeles,Fresno,Fresno,2012,Freshman,DESIGN SCIENCE HIGH SCHOOL,NaN,3.818000,NaN
3,BLOOMFIELD HILLS HIGH SCHOOL232447,Universitywide,Bloomfield Twp,Michigan,2015,Freshman,BLOOMFIELD HILLS HIGH SCHOOL,3.942,3.950000,NaN
4,A B MILLER HIGH SCHOOL050944,Santa Barbara,Fontana,San Bernardino,1998,Freshman,A B MILLER HIGH SCHOOL,NaN,3.518571,NaN

In [4]:
len(gpa)

333312

In [5]:
gpa_1 = gpa.drop_duplicates(subset='Fall Term', keep='first')
gpa_1

,Calculation1,Campus,City,County/State/Country,Fall Term,Level,School,Adm GPA (SUM),App GPA (SUM),Enrl GPA (SUM)
0,GERMAN SWISS INTERNATIONAL SCH670905,Berkeley,NaN,HONG KONG,2012,Freshman,GERMAN SWISS INTERNATIONAL SCH,NaN,3.604000,NaN
1,AQUINAS HIGH SCHOOL052772,Riverside,San Bernardino,San Bernardino,1995,Freshman,AQUINAS HIGH SCHOOL,NaN,3.361429,NaN
3,BLOOMFIELD HILLS HIGH SCHOOL232447,Universitywide,Bloomfield Twp,Michigan,2015,Freshman,BLOOMFIELD HILLS HIGH SCHOOL,3.942000,3.950000,NaN
4,A B MILLER HIGH SCHOOL050944,Santa Barbara,Fontana,San Bernardino,1998,Freshman,A B MILLER HIGH SCHOOL,NaN,3.518571,NaN
5,WAYZATA HIGH SCHOOL242650,Davis,Plymouth,Minnesota,2013,Freshman,WAYZATA HIGH SCHOOL,NaN,3.660000,NaN
8,JAMES A GARFIELD HIGH SCHOOL051635,Berkeley,Los Angeles,Los Angeles,2014,Freshman,JAMES A GARFIELD HIGH SCHOOL,4.118000,3.762895,4.055714
9,MONTEREY HIGH SCHOOL052050,Universitywide,Monterey,Monterey,2004,Freshman,MONTEREY HIGH SCHOOL,3.834565,3.714545,3.812759
11,BENTONVILLE HIGH SCHOOL040175,Berkeley,Bentonville,Arkansas,2017,Freshman,BENTONVILLE HIGH SCHOOL,NaN,4.001250,NaN
12,ABRAHAM LINCOLN HIGH SCHOOL051520,Universitywide,Los Angeles,Los Angeles,2008,Freshman,ABRAHAM LINCOLN HIGH SCHOOL,3.566000,3.413882,3.609592
14,AMADOR VALLEY HIGH SCHOOL052495,Santa Cruz,Pleasanton,Alameda,2003,Freshman,AMADOR VALLEY HIGH SCHOOL,3.582174,3.574400,3.415000
16,ARNOLD O BECKMAN HIGH SCHOOL051267,Santa Cruz,Irvine,Orange,2007,Freshman,ARNOLD O BECKMAN HIGH SCHOOL,3.622917,3.501034,NaN
20,HANFORD HIGH SCHOOL051130,Santa Barbara,Hanford,Kings,1996,Freshman,HANFORD HIGH SCHOOL,NaN,3.198333,NaN
22,SHELDON HIGH SCHOOL052792,Universitywide,Sacramento,Sacramento,2010,Freshman,SHELDON HIGH SCHOOL,3.775172,3.728154,3.878286
23,MONTGOMERY HIGH SCHOOL053328,Universitywide,Santa Rosa,Sonoma,1994,Freshman,MONTGOMERY HIGH SCHOOL,3.885075,3.830417,3.864054
26,RANCHO COTATE HIGH SCHOOL052678,Santa Cruz,Rohnert Park,Sonoma,1999,Freshman,RANCHO COTATE HIGH SCHOOL,3.780000,3.584000,NaN
27,OAK PARK HIGH SCHOOL050006,Davis,Oak Park,Ventura,1997,Freshman,OAK PARK HIGH SCHOOL,3.920000,3.826429,NaN
31,ARCHBISHOP RIORDAN HIGH SCHOOL053000,Merced,San Francisco,San Francisco,2005,Freshman,ARCHBISHOP RIORDAN HIGH SCHOOL,3.336667,3.305385,NaN
34,ACADEMY OF MEDICAL ARTS AT CARSON054618,Santa Barbara,Carson,Los Angeles,2016,Freshman,ACADEMY OF MEDICAL ARTS AT CARSON,NaN,3.795556,NaN
38,CASTILLEJA SCHOOL052330,Riverside,Palo Alto,Santa Clara,2000,Freshman,CASTILLEJA SCHOOL,3.585714,3.585714,NaN
58,A B MILLER HIGH SCHOOL050944,Irvine,Fontana,San Bernardino,2011,Freshman,A B MILLER HIGH SCHOOL,3.894615,3.536216,NaN
59,ADLAI E STEVENSON HIGH SCHOOL143550,Berkeley,Lincolnshire,Illinois,2006,Freshman,ADLAI E STEVENSON HIGH SCHOOL,NaN,4.033333,NaN
65,DOMINGUEZ SENIOR HIGH SCHOOL050652,Santa Cruz,Compton,Los Angeles,2009,Freshman,DOMINGUEZ SENIOR HIGH SCHOOL,3.588000,3.205333,NaN
74,POINT LOMA HIGH SCHOOL052870,Riverside,San Diego,San Diego,2002,Freshman,POINT LOMA HIGH SCHOOL,3.517857,3.601765,NaN
118,SANTA BARBARA SENIOR HIGH SCHO053275,Berkeley,Santa Barbara,Santa Barbara,2001,Freshman,SANTA BARBARA SENIOR HIGH SCHO,4.170800,3.939500,4.066667

In [6]:
len(gpa_1)

24

In [7]:
transfers = pd.read_csv("Transfers.csv")

In [8]:
transfers.head()

,Calculation1,Campus,City,County/State/ Territory,Fall Term,School,Sch Src TR,Uad Uc Ethn 6 Cat,adm (SUM),app (SUM),enr (SUM)
0,BUTTE COLLEGE4226,Davis,Oroville,Butte,2007,BUTTE COLLEGE,California Community Colleges (CCC),White,22.0,32,4.0
1,IMPERIAL VALLEY COLLEGE4358,Riverside,Imperial,Imperial,2008,IMPERIAL VALLEY COLLEGE,California Community Colleges (CCC),Hispanic/ Latino,13.0,27,3.0
2,ALLAN HANCOCK COLLEGE4002,Universitywide,Santa Maria,Santa Barbara,2012,ALLAN HANCOCK COLLEGE,California Community Colleges (CCC),White,97.0,133,65.0
3,AMERICAN RIVER COLLEGE4004,Berkeley,Sacramento,Sacramento,1996,AMERICAN RIVER COLLEGE,California Community Colleges (CCC),Hispanic/ Latino,8.0,14,6.0
4,CUESTA COLLEGE4101,Santa Barbara,San Luis Obispo,San Luis Obispo,2013,CUESTA COLLEGE,California Community Colleges (CCC),All,122.0,262,42.0

In [9]:
len(transfers)

103965

In [10]:
transfers_1 = transfers.drop_duplicates(subset='Fall Term', keep='first')
transfers_1

,Calculation1,Campus,City,County/State/ Territory,Fall Term,School,Sch Src TR,Uad Uc Ethn 6 Cat,adm (SUM),app (SUM),enr (SUM)
0,BUTTE COLLEGE4226,Davis,Oroville,Butte,2007,BUTTE COLLEGE,California Community Colleges (CCC),White,22.0,32,4.0
1,IMPERIAL VALLEY COLLEGE4358,Riverside,Imperial,Imperial,2008,IMPERIAL VALLEY COLLEGE,California Community Colleges (CCC),Hispanic/ Latino,13.0,27,3.0
2,ALLAN HANCOCK COLLEGE4002,Universitywide,Santa Maria,Santa Barbara,2012,ALLAN HANCOCK COLLEGE,California Community Colleges (CCC),White,97.0,133,65.0
3,AMERICAN RIVER COLLEGE4004,Berkeley,Sacramento,Sacramento,1996,AMERICAN RIVER COLLEGE,California Community Colleges (CCC),Hispanic/ Latino,8.0,14,6.0
4,CUESTA COLLEGE4101,Santa Barbara,San Luis Obispo,San Luis Obispo,2013,CUESTA COLLEGE,California Community Colleges (CCC),All,122.0,262,42.0
5,COLLEGE OF THE DESERT4085,Riverside,Palm Desert,Riverside,2015,COLLEGE OF THE DESERT,California Community Colleges (CCC),White,14.0,34,6.0
8,BUTTE COLLEGE4226,Santa Barbara,Oroville,Butte,2003,BUTTE COLLEGE,California Community Colleges (CCC),All,13.0,24,NaN
9,ALLAN HANCOCK COLLEGE4002,Universitywide,Santa Maria,Santa Barbara,2002,ALLAN HANCOCK COLLEGE,California Community Colleges (CCC),Hispanic/ Latino,50.0,69,32.0
11,AMERICAN RIVER COLLEGE4004,Davis,Sacramento,Sacramento,2010,AMERICAN RIVER COLLEGE,California Community Colleges (CCC),Asian,82.0,124,52.0
12,MIRACOSTA COLLEGE4582,Universitywide,Oceanside,San Diego,1997,MIRACOSTA COLLEGE,California Community Colleges (CCC),Inter- national,8.0,10,6.0
14,CHAFFEY COLLEGE4046,Berkeley,Rnch Cmnga,San Bernardino,2000,CHAFFEY COLLEGE,California Community Colleges (CCC),Asian,NaN,16,NaN
16,ANTELOPE VALLEY COLLEGE4005,Santa Barbara,Lancaster,Los Angeles,2004,ANTELOPE VALLEY COLLEGE,California Community Colleges (CCC),Hispanic/ Latino,21.0,32,NaN
17,ALLAN HANCOCK COLLEGE4002,Universitywide,Santa Maria,Santa Barbara,1994,ALLAN HANCOCK COLLEGE,California Community Colleges (CCC),All,72.0,100,46.0
18,SIERRA COLLEGE4697,Santa Cruz,Rocklin,Placer,1999,SIERRA COLLEGE,California Community Colleges (CCC),White,32.0,58,NaN
19,ALLAN HANCOCK COLLEGE4002,Universitywide,Santa Maria,Santa Barbara,1995,ALLAN HANCOCK COLLEGE,California Community Colleges (CCC),Hispanic/ Latino,30.0,34,24.0
21,DIABLO VALLEY COLLEGE4295,San Diego,Pleasant Hill,Contra Costa,2017,DIABLO VALLEY COLLEGE,California Community Colleges (CCC),African American,34.0,44,12.0
23,SAN DIEGO MESA COLLEGE4735,San Diego,San Diego,San Diego,2001,SAN DIEGO MESA COLLEGE,California Community Colleges (CCC),Inter- national,15.0,21,11.0
25,BARSTOW COLLEGE4020,Los Angeles,Barstow,San Bernardino,2005,BARSTOW COLLEGE,California Community Colleges (CCC),All,NaN,12,NaN
26,UC BERKELEY4833,Universitywide,Berkeley,Alameda,2009,UC BERKELEY,University of California (UC),All,75.0,103,35.0
29,GLENDALE COMMUNITY COLLEGE4327,Santa Cruz,Glendale,Los Angeles,2011,GLENDALE COMMUNITY COLLEGE,California Community Colleges (CCC),White,76.0,112,6.0
33,MARYMOUNT CALIFORNIA UNIVERSITY4515,Irvine,Rancho Palos Verdes,Los Angeles,1998,MARYMOUNT CALIFORNIA UNIVERSITY,CA Private Institutions,Asian,10.0,16,6.0
44,PALOMAR COLLEGE4602,Riverside,San Marcos,San Diego,2006,PALOMAR COLLEGE,California Community Colleges (CCC),Hispanic/ Latino,10.0,12,NaN
61,VICTOR VALLEY COLLEGE4932,Universitywide,Victorville,San Bernardino,2014,VICTOR VALLEY COLLEGE,California Community Colleges (CCC),African American,NaN,10,NaN
115,ALLAN HANCOCK COLLEGE4002,Santa Barbara,Santa Maria,Santa Barbara,2016,ALLAN HANCOCK COLLEGE,California Community Colleges (CCC),Hispanic/ Latino,80.0,134,44.0

In [11]:
len(transfers_1)

24

In [12]:
freshmen = pd.read_csv("Freshmen.csv")

In [13]:
freshmen.head()

,Calculation1,Campus,City,County/State/ Territory,Fall Term,School,Sch Src FR,Uad Uc Ethn 6 Cat,adm (SUM),app (SUM),enr (SUM)
0,F BRAVO MEDICAL MAGNET HS51719,Riverside,Los Angeles,Los Angeles,2008,F BRAVO MEDICAL MAGNET HS,California Public High School,Hispanic/ Latino,39.0,50,10.0
1,ARAGON HIGH SCHOOL53163,Santa Barbara,San Mateo,San Mateo,2012,ARAGON HIGH SCHOOL,California Public High School,Asian,28.0,53,4.0
2,ETIWANDA HIGH SCHOOL50888,San Diego,Etiwanda,San Bernardino,2012,ETIWANDA HIGH SCHOOL,California Public High School,Asian,11.0,34,4.0
3,UPLAND HIGH SCHOOL53586,Merced,Upland,San Bernardino,2005,UPLAND HIGH SCHOOL,California Public High School,Asian,6.0,7,NaN
4,MORNINGSIDE HIGH SCHOOL51262,Los Angeles,Inglewood,Los Angeles,2006,MORNINGSIDE HIGH SCHOOL,California Public High School,All,5.0,22,NaN

In [14]:
len(freshmen)

587501

In [17]:
freshmen_1 = freshmen.drop_duplicates(subset='Fall Term', keep='first')
freshmen_1

,Calculation1,Campus,City,County/State/ Territory,Fall Term,School,Sch Src FR,Uad Uc Ethn 6 Cat,adm (SUM),app (SUM),enr (SUM)
0,F BRAVO MEDICAL MAGNET HS51719,Riverside,Los Angeles,Los Angeles,2008,F BRAVO MEDICAL MAGNET HS,California Public High School,Hispanic/ Latino,39.0,50,10.0
1,ARAGON HIGH SCHOOL53163,Santa Barbara,San Mateo,San Mateo,2012,ARAGON HIGH SCHOOL,California Public High School,Asian,28.0,53,4.0
3,UPLAND HIGH SCHOOL53586,Merced,Upland,San Bernardino,2005,UPLAND HIGH SCHOOL,California Public High School,Asian,6.0,7,NaN
4,MORNINGSIDE HIGH SCHOOL51262,Los Angeles,Inglewood,Los Angeles,2006,MORNINGSIDE HIGH SCHOOL,California Public High School,All,5.0,22,NaN
6,MIDDLE COLLEGE HIGH SCHOOL53204,Los Angeles,San Pablo,Contra Costa,2003,MIDDLE COLLEGE HIGH SCHOOL,California Public High School,Asian,4.0,6,NaN
7,BROOKWOOD HIGH SCHOOL112754,Universitywide,Snellville,Georgia,2016,BROOKWOOD HIGH SCHOOL,Non-CA Domestic High School,All,5.0,8,NaN
8,CHAFFEY HIGH SCHOOL52275,Universitywide,Ontario,San Bernardino,2011,CHAFFEY HIGH SCHOOL,California Public High School,Asian,6.0,8,3.0
9,VICTOR VALLEY HIGH SCHOOL53660,Universitywide,Victorville,San Bernardino,1999,VICTOR VALLEY HIGH SCHOOL,California Public High School,Asian,4.0,5,3.0
13,ESTANCIA HIGH SCHOOL50684,Universitywide,Costa Mesa,Orange,2009,ESTANCIA HIGH SCHOOL,California Public High School,Asian,7.0,7,3.0
14,WARREN HIGH SCHOOL50771,Universitywide,Downey,Los Angeles,1998,WARREN HIGH SCHOOL,California Public High School,All,45.0,53,26.0
15,AMITY REGIONAL HIGH SCHOOL70965,Universitywide,Woodbridge,Connecticut,1996,AMITY REGIONAL HIGH SCHOOL,Non-CA Domestic High School,All,NaN,5,NaN
19,BRAWLEY UNION HIGH SCHOOL50365,Universitywide,Brawley,Imperial,2000,BRAWLEY UNION HIGH SCHOOL,California Public High School,Hispanic/ Latino,11.0,14,4.0
21,CHENGDU SHUDE HIGH SCHOOL694370,San Diego,NaN,"CHINA, PEOPLES REPUBLIC",2015,CHENGDU SHUDE HIGH SCHOOL,Foreign Institution,All,9.0,37,3.0
25,ACADEMY OF THE CANYONS53262,Universitywide,Santa Clarita,Los Angeles,2013,ACADEMY OF THE CANYONS,California Public High School,White,7.0,15,4.0
27,CLOVIS EAST HIGH SCHOOL50622,Davis,Clovis,Fresno,2007,CLOVIS EAST HIGH SCHOOL,California Public High School,Asian,8.0,16,4.0
28,JEFFERSON HIGH SCHOOL50720,Universitywide,Daly City,San Mateo,2014,JEFFERSON HIGH SCHOOL,California Public High School,Asian,14.0,24,8.0
32,LANCASTER HIGH SCHOOL51412,Berkeley,Lancaster,Los Angeles,2017,LANCASTER HIGH SCHOOL,California Public High School,All,NaN,18,NaN
38,AMOS ALONZO STAGG HIGH SCHOOL53442,Santa Barbara,Stockton,San Joaquin,2004,AMOS ALONZO STAGG HIGH SCHOOL,California Public High School,All,8.0,9,4.0
41,A B MILLER HIGH SCHOOL50944,Universitywide,Fontana,San Bernardino,2002,A B MILLER HIGH SCHOOL,California Public High School,All,55.0,72,34.0
63,A B MILLER HIGH SCHOOL50944,Riverside,Fontana,San Bernardino,1994,A B MILLER HIGH SCHOOL,California Public High School,All,27.0,31,11.0
66,DREW SCHOOL52940,Santa Cruz,San Francisco,San Francisco,2001,DREW SCHOOL,California Private High School,All,11.0,12,6.0
69,ARMIJO HIGH SCHOOL50910,Universitywide,Fairfield,Solano,2010,ARMIJO HIGH SCHOOL,California Public High School,Asian,24.0,25,10.0
72,SCHURR HIGH SCHOOL52037,San Diego,Montebello,Los Angeles,1997,SCHURR HIGH SCHOOL,California Public High School,Asian,23.0,42,NaN
87,MARK KEPPEL HIGH SCHOOL50055,Davis,Alhambra,Los Angeles,1995,MARK KEPPEL HIGH SCHOOL,California Public High School,Asian,NaN,14,NaN

In [18]:
len(freshmen_1)

24

In [19]:
freshmen.sort_values('adm (SUM)', ascending=False)

,Calculation1,Campus,City,County/State/ Territory,Fall Term,School,Sch Src FR,Uad Uc Ethn 6 Cat,adm (SUM),app (SUM),enr (SUM)
39896,INSTITUTION IN THE FAR EAST989345,Universitywide,NaN,"CHINA, PEOPLES REPUBLIC",2015,INSTITUTION IN THE FAR EAST,Foreign Institution,All,1564.0,2312,689.0
20557,INSTITUTION IN THE FAR EAST989345,Universitywide,NaN,"CHINA, PEOPLES REPUBLIC",2015,INSTITUTION IN THE FAR EAST,Foreign Institution,Inter- national,1537.0,2261,677.0
581037,INSTITUTION IN THE FAR EAST989345,Irvine,NaN,"CHINA, PEOPLES REPUBLIC",2015,INSTITUTION IN THE FAR EAST,Foreign Institution,All,1410.0,2312,658.0
581045,INSTITUTION IN THE FAR EAST989345,Irvine,NaN,"CHINA, PEOPLES REPUBLIC",2015,INSTITUTION IN THE FAR EAST,Foreign Institution,Inter- national,1385.0,2261,646.0
417743,INSTITUTION IN THE FAR EAST989345,Universitywide,NaN,"CHINA, PEOPLES REPUBLIC",2014,INSTITUTION IN THE FAR EAST,Foreign Institution,All,1038.0,1848,395.0
581029,INSTITUTION IN THE FAR EAST989345,Universitywide,NaN,"CHINA, PEOPLES REPUBLIC",2014,INSTITUTION IN THE FAR EAST,Foreign Institution,Inter- national,1014.0,1800,386.0
430862,INSTITUTION IN THE FAR EAST989345,Universitywide,NaN,"CHINA, PEOPLES REPUBLIC",2013,INSTITUTION IN THE FAR EAST,Foreign Institution,All,965.0,1542,363.0
581028,INSTITUTION IN THE FAR EAST989345,Universitywide,NaN,"CHINA, PEOPLES REPUBLIC",2013,INSTITUTION IN THE FAR EAST,Foreign Institution,Inter- national,939.0,1504,351.0
546413,INSTITUTION IN THE FAR EAST989345,Irvine,NaN,"CHINA, PEOPLES REPUBLIC",2014,INSTITUTION IN THE FAR EAST,Foreign Institution,All,890.0,1848,377.0
581036,INSTITUTION IN THE FAR EAST989345,Irvine,NaN,"CHINA, PEOPLES REPUBLIC",2013,INSTITUTION IN THE FAR EAST,Foreign Institution,All,885.0,1542,348.0
197714,INSTITUTION IN THE FAR EAST989345,Irvine,NaN,"CHINA, PEOPLES REPUBLIC",2014,INSTITUTION IN THE FAR EAST,Foreign Institution,Inter- national,868.0,1800,368.0
581044,INSTITUTION IN THE FAR EAST989345,Irvine,NaN,"CHINA, PEOPLES REPUBLIC",2013,INSTITUTION IN THE FAR EAST,Foreign Institution,Inter- national,859.0,1504,336.0
581018,INSTITUTION IN THE FAR EAST989345,Universitywide,NaN,"CHINA, PEOPLES REPUBLIC",2012,INSTITUTION IN THE FAR EAST,Foreign Institution,All,591.0,808,233.0
581035,INSTITUTION IN THE FAR EAST989345,Irvine,NaN,"CHINA, PEOPLES REPUBLIC",2012,INSTITUTION IN THE FAR EAST,Foreign Institution,All,583.0,808,232.0
306875,INSTITUTION IN THE FAR EAST989345,Universitywide,NaN,"CHINA, PEOPLES REPUBLIC",2012,INSTITUTION IN THE FAR EAST,Foreign Institution,Inter- national,576.0,783,226.0
580797,INSTITUTION IN THE FAR EAST989345,Irvine,NaN,"CHINA, PEOPLES REPUBLIC",2012,INSTITUTION IN THE FAR EAST,Foreign Institution,Inter- national,569.0,783,226.0
78104,LOWELL HIGH SCHOOL52970,Universitywide,San Francisco,San Francisco,2010,LOWELL HIGH SCHOOL,California Public High School,All,491.0,540,313.0
581053,INSTITUTION IN THE FAR EAST989345,Santa Cruz,NaN,"CHINA, PEOPLES REPUBLIC",2015,INSTITUTION IN THE FAR EAST,Foreign Institution,All,490.0,696,31.0
92655,INSTITUTION IN THE FAR EAST989345,Santa Cruz,NaN,"CHINA, PEOPLES REPUBLIC",2015,INSTITUTION IN THE FAR EAST,Foreign Institution,Inter- national,482.0,680,NaN
209287,LOWELL HIGH SCHOOL52970,Universitywide,San Francisco,San Francisco,2006,LOWELL HIGH SCHOOL,California Public High School,All,479.0,507,332.0
321188,LOWELL HIGH SCHOOL52970,Universitywide,San Francisco,San Francisco,2005,LOWELL HIGH SCHOOL,California Public High School,All,475.0,516,337.0
55294,ARCADIA HIGH SCHOOL50130,Universitywide,Arcadia,Los Angeles,2008,ARCADIA HIGH SCHOOL,California Public High School,All,472.0,508,291.0
356589,LOWELL HIGH SCHOOL52970,Universitywide,San Francisco,San Francisco,2007,LOWELL HIGH SCHOOL,California Public High School,All,467.0,501,317.0
281653,LOWELL HIGH SCHOOL52970,Universitywide,San Francisco,San Francisco,2008,LOWELL HIGH SCHOOL,California Public High School,All,462.0,509,286.0
356588,LOWELL HIGH SCHOOL52970,Universitywide,San Francisco,San Francisco,2003,LOWELL HIGH SCHOOL,California Public High School,All,460.0,529,291.0
71306,ARCADIA HIGH SCHOOL50130,Universitywide,Arcadia,Los Angeles,2009,ARCADIA HIGH SCHOOL,California Public High School,All,459.0,512,269.0
93719,ARCADIA HIGH SCHOOL50130,Universitywide,Arcadia,Los Angeles,2006,ARCADIA HIGH SCHOOL,California Public High School,All,458.0,494,291.0
193561,LOWELL HIGH SCHOOL52970,Universitywide,San Francisco,San Francisco,2004,LOWELL HIGH SCHOOL,California Public High School,All,449.0,529,337.0
356590,LOWELL HIGH SCHOOL52970,Universitywide,San Francisco,San Francisco,2011,LOWELL HIGH SCHOOL,California Public High School,All,447.0,531,309.0
342822,TORREY PINES HIGH SCHOOL50466,Universitywide,Encinitas,San Diego,2007,TORREY PINES HIGH SCHOOL,California Public High School,All,442.0,476,177.0
...,...,...,...,...,...,...,...,...,...,...,...
587363,YORK MILLS COLLEGIATE INST826961,Los Angeles,NaN,CANADA,2016,YORK MILLS COLLEGIATE INST,Foreign Institution,All,NaN,5,NaN
587365,YUEZHOU HIGH SCHOOL694441,Universitywide,NaN,"CHINA, PEOPLES REPUBLIC",2015,YUEZHOU HIGH SCHOOL,Foreign Institution,Inter- national,NaN,9,NaN
587367,YUEZHOU HIGH SCHOOL694441,Irvine,NaN,"CHINA, PEOPLES REPUBLIC",2015,YUEZHOU HIGH SCHOOL,Foreign Institution,Inter- national,NaN,8,NaN
587372,ZAMA AMERICAN HIGH SCHOOL DOD561980,Universitywide,NaN,JAPAN,2013,ZAMA AMERICAN HIGH SCHOOL DOD,Foreign Institution,All,NaN,7,NaN
587374,ZAMA AMERICAN HIGH SCHOOL DOD561980,Universitywide,NaN,JAPAN,2013,ZAMA AMERICAN HIGH SCHOOL DOD,Foreign Institution,Asian,NaN,6,NaN
587376,ZHANGJIAGANG IVY EXPERIMENTAL694355,Berkeley,NaN,"CHINA, PEOPLES REPUBLIC",2015,ZHANGJIAGANG IVY EXPERIMENTAL,Foreign Institution,All,NaN,9,NaN
587377,ZHANGJIAGANG IVY EXPERIMENTAL694355,Berkeley,NaN,"CHINA, PEOPLES REPUBLIC",2016,ZHANGJIAGANG IVY EXPERIMENTAL,Foreign Institution,All,NaN,16,NaN
587407,ZHEJIANG JINHUA AIQING SCHOOL694480,Irvine,NaN,"CHINA, PEOPLES REPUBLIC",2016,ZHEJIANG JINHUA AIQING SCHOOL,Foreign Institution,All,NaN,5,NaN
587410,ZHENGZHOU FOREIGN LANGUAGE SCH694361,Universitywide,NaN,"CHINA, PEOPLES REPUBLIC",2012,ZHENGZHOU FOREIGN LANGUAGE SCH,Foreign Institution,Inter- national,NaN,30,NaN
587413,ZHENGZHOU FOREIGN LANGUAGE SCH694361,Berkeley,NaN,"CHINA, PEOPLES REPUBLIC",2014,ZHENGZHOU FOREIGN LANGUAGE SCH,Foreign Institution,Inter- national,NaN,27,NaN
587414,ZHENGZHOU FOREIGN LANGUAGE SCH694361,Berkeley,NaN,"CHINA, PEOPLES REPUBLIC",2016,ZHENGZHOU FOREIGN LANGUAGE SCH,Foreign Institution,Inter- national,NaN,46,NaN
587418,ZHENGZHOU FOREIGN LANGUAGE SCH694361,Irvine,NaN,"CHINA, PEOPLES REPUBLIC",2011,ZHENGZHOU FOREIGN LANGUAGE SCH,Foreign Institution,All,NaN,5,NaN
587424,ZHENGZHOU FOREIGN LANGUAGE SCH694361,Los Angeles,NaN,"CHINA, PEOPLES REPUBLIC",2014,ZHENGZHOU FOREIGN LANGUAGE SCH,Foreign Institution,All,NaN,38,NaN
587426,ZHENGZHOU FOREIGN LANGUAGE SCH694361,Los Angeles,NaN,"CHINA, PEOPLES REPUBLIC",2012,ZHENGZHOU FOREIGN LANGUAGE SCH,Foreign Institution,Inter- national,NaN,26,NaN
587427,ZHENGZHOU FOREIGN LANGUAGE SCH694361,Los Angeles,NaN,"CHINA, PEOPLES REPUBLIC",2014,ZHENGZHOU FOREIGN LANGUAGE SCH,Foreign Institution,Inter- national,NaN,36,NaN
587428,ZHENGZHOU FOREIGN LANGUAGE SCH694361,Los Angeles,NaN,"CHINA, PEOPLES REPUBLIC",2016,ZHENGZHOU FOREIGN LANGUAGE SCH,Foreign Institution,Inter- national,NaN,55,NaN
587441,ZHENGZHOU MIDDLE SCHOOL694448,Los Angeles,NaN,"CHINA, PEOPLES REPUBLIC",2013,ZHENGZHOU MIDDLE SCHOOL,Foreign Institution,All,NaN,6,NaN
587452,ZHENGZHOU NO 7 MIDDLE SCHOOL694440,Los Angeles,NaN,"CHINA, PEOPLES REPUBLIC",2015,ZHENGZHOU NO 7 MIDDLE SCHOOL,Foreign Institution,All,NaN,11,NaN
587453,ZHENGZHOU NO 7 MIDDLE SCHOOL694440,Los Angeles,NaN,"CHINA, PEOPLES REPUBLIC",2016,ZHENGZHOU NO 7 MIDDLE SCHOOL,Foreign Institution,All,NaN,14,NaN
587460,ZHENGZHOU NO 11 MIDDLE SCHOOL694432,San Diego,NaN,"CHINA, PEOPLES REPUBLIC",2016,ZHENGZHOU NO 11 MIDDLE SCHOOL,Foreign Institution,All,NaN,7,NaN
587464,ZHENGZHOU NO 47 MIDDLE & HIGH694388,Davis,NaN,"CHINA, PEOPLES REPUBLIC",2015,ZHENGZHOU NO 47 MIDDLE & HIGH,Foreign Institution,All,NaN,5,NaN
587466,ZHENGZHOU NO 47 MIDDLE & HIGH694388,Irvine,NaN,"CHINA, PEOPLES REPUBLIC",2016,ZHENGZHOU NO 47 MIDDLE & HIGH,Foreign Institution,All,NaN,5,NaN
587474,ZHENHAI HIGH SCH OF ZHEJIANG694294,Berkeley,NaN,"CHINA, PEOPLES REPUBLIC",2013,ZHENHAI HIGH SCH OF ZHEJIANG,Foreign Institution,All,NaN,22,NaN
587475,ZHENHAI HIGH SCH OF ZHEJIANG694294,Berkeley,NaN,"CHINA, PEOPLES REPUBLIC",2013,ZHENHAI HIGH SCH OF ZHEJIANG,Foreign Institution,Inter- national,NaN,21,NaN
587476,ZHENHAI HIGH SCH OF ZHEJIANG694294,Davis,NaN,"CHINA, PEOPLES REPUBLIC",2013,ZHENHAI HIGH SCH OF ZHEJIANG,Foreign Institution,Inter- national,NaN,19,NaN
587480,ZHENHAI HIGH SCH OF ZHEJIANG694294,Los Angeles,NaN,"CHINA, PEOPLES REPUBLIC",2016,ZHENHAI HIGH SCH OF ZHEJIANG,Foreign Institution,Inter- national,NaN,29,NaN
587484,ZHENHAI HIGH SCH OF ZHEJIANG694294,San Diego,NaN,"CHINA, PEOPLES REPUBLIC",2016,ZHENHAI HIGH SCH OF ZHEJIANG,Foreign Institution,Inter- national,NaN,39,NaN
587490,ZHUHAI NO 1 HIGH SCHOOL694565,Los Angeles,NaN,"CHINA, PEOPLES REPUBLIC",2015,ZHUHAI NO 1 HIGH SCHOOL,Foreign Institution,All,NaN,13,NaN
587493,ZIBO EXPERIMENTAL HIGH SCHOOL694601,Universitywide,NaN,"CHINA, PEOPLES REPUBLIC",2016,ZIBO EXPERIMENTAL HIGH SCHOOL,Foreign Institution,All,NaN,6,NaN
587499,ZURICH INTERNATIONAL SCHOOL796330,Los Angeles,NaN,SWITZERLAND,2017,ZURICH INTERNATIONAL SCHOOL,Foreign Institution,All,NaN,6,NaN

In [33]:
freshmen.sort_values('adm (SUM)')

,Calculation1,Campus,City,County/State/ Territory,Fall Term,School,Sch Src FR,Uad Uc Ethn 6 Cat,adm (SUM),app (SUM),enr (SUM)
180511,CENTRAL VALLEY HIGH SCHOOL53988,Berkeley,Ceres,Stanislaus,2015,CENTRAL VALLEY HIGH SCHOOL,California Public High School,All,3.0,22,NaN
576035,WILTON HIGH SCHOOL70938,Universitywide,Wilton,Connecticut,2015,WILTON HIGH SCHOOL,Non-CA Domestic High School,White,3.0,12,NaN
166274,JAMES C ENOCHS HIGH SCHOOL54043,San Diego,Modesto,Stanislaus,2017,JAMES C ENOCHS HIGH SCHOOL,California Public High School,White,3.0,10,NaN
166273,CRYSTAL SPRINGS UPLANDS SCH51173,Los Angeles,Hillsborough,San Mateo,1997,CRYSTAL SPRINGS UPLANDS SCH,California Private High School,Asian,3.0,6,NaN
522345,FOREST LAKE CHRISTIAN SCHOOL50173,Davis,Auburn,Placer,2004,FOREST LAKE CHRISTIAN SCHOOL,California Private High School,All,3.0,5,NaN
356205,BISHOP ALEMANY HIGH SCHOOL52898,Irvine,Mission Hills,Los Angeles,2013,BISHOP ALEMANY HIGH SCHOOL,California Private High School,Hispanic/ Latino,3.0,10,NaN
356209,EASTSIDE CHRISTIAN HIGH SCHOOL50086,Irvine,Fullerton,Orange,2017,EASTSIDE CHRISTIAN HIGH SCHOOL,California Private High School,All,3.0,10,NaN
55498,HARBOR HIGH SCHOOL53293,San Diego,Santa Cruz,Santa Cruz,2016,HARBOR HIGH SCHOOL,California Public High School,White,3.0,12,NaN
506306,WOODROW WILSON HIGH SCHOOL51840,Irvine,Los Angeles,Los Angeles,2015,WOODROW WILSON HIGH SCHOOL,California Public High School,Asian,3.0,6,NaN
166254,DIOCESAN GIRLS SCHOOL670480,Universitywide,NaN,HONG KONG,1996,DIOCESAN GIRLS SCHOOL,Foreign Institution,All,3.0,7,NaN
447484,SYLMAR HIGH SCHOOL52908,Berkeley,Sylmar,Los Angeles,2017,SYLMAR HIGH SCHOOL,California Public High School,Hispanic/ Latino,3.0,24,NaN
522339,FOREST LAKE CHRISTIAN SCHOOL50173,Universitywide,Auburn,Placer,2016,FOREST LAKE CHRISTIAN SCHOOL,California Private High School,All,3.0,6,3.0
166284,JAMES LOGAN HIGH SCHOOL50969,Riverside,Union City,Alameda,2012,JAMES LOGAN HIGH SCHOOL,California Public High School,Hispanic/ Latino,3.0,10,NaN
166234,CANYON HIGH SCHOOL53341,Irvine,Canyon Country,Los Angeles,2010,CANYON HIGH SCHOOL,California Public High School,Asian,3.0,9,NaN
55512,CASTLE PARK HIGH SCHOOL50573,San Diego,Chula Vista,San Diego,2012,CASTLE PARK HIGH SCHOOL,California Public High School,Hispanic/ Latino,3.0,33,NaN
55513,PACIFICA HIGH SCHOOL52379,Santa Cruz,Oxnard,Ventura,2008,PACIFICA HIGH SCHOOL,California Public High School,All,3.0,7,NaN
166223,MONTEREY HIGH SCHOOL52050,Irvine,Monterey,Monterey,1994,MONTEREY HIGH SCHOOL,California Public High School,All,3.0,5,NaN
55518,NARBONNE HIGH SCHOOL51140,San Diego,Harbor City,Los Angeles,2003,NARBONNE HIGH SCHOOL,California Public High School,Hispanic/ Latino,3.0,8,NaN
55519,WOODSIDE INTERNATIONAL SCHOOL53044,Universitywide,San Francisco,San Francisco,2013,WOODSIDE INTERNATIONAL SCHOOL,California Private High School,All,3.0,6,NaN
576030,WILSONVILLE HIGH SCHOOL381258,San Diego,Wilsonville,Oregon,2008,WILSONVILLE HIGH SCHOOL,Non-CA Domestic High School,White,3.0,5,NaN
55538,SEQUOIA HIGH SCHOOL52605,Davis,Redwood City,San Mateo,2005,SEQUOIA HIGH SCHOOL,California Public High School,Hispanic/ Latino,3.0,7,NaN
166193,CANYON HIGH SCHOOL53341,Irvine,Canyon Country,Los Angeles,2011,CANYON HIGH SCHOOL,California Public High School,Hispanic/ Latino,3.0,10,NaN
576027,WILSONVILLE HIGH SCHOOL381258,Los Angeles,Wilsonville,Oregon,2015,WILSONVILLE HIGH SCHOOL,Non-CA Domestic High School,All,3.0,10,NaN
166182,VILLAGE CHRISTIAN HIGH SCHOOL53468,Santa Cruz,Sun Valley,Los Angeles,2015,VILLAGE CHRISTIAN HIGH SCHOOL,California Private High School,Asian,3.0,7,NaN
55548,APTOS HIGH SCHOOL50119,Santa Barbara,Aptos,Santa Cruz,1995,APTOS HIGH SCHOOL,California Public High School,Hispanic/ Latino,3.0,5,NaN
576031,WILTON HIGH SCHOOL70938,Universitywide,Wilton,Connecticut,2000,WILTON HIGH SCHOOL,Non-CA Domestic High School,All,3.0,5,NaN
166287,CANYON HIGH SCHOOL53341,Riverside,Canyon Country,Los Angeles,2002,CANYON HIGH SCHOOL,California Public High School,Asian,3.0,5,NaN
555674,DEERFIELD ACADEMY220685,Universitywide,Deerfield,Massachusetts,2006,DEERFIELD ACADEMY,Non-CA Domestic High School,White,3.0,7,NaN
447514,MARIN CATHOLIC HIGH SCHOOL53215,Irvine,Kentfield,Marin,1996,MARIN CATHOLIC HIGH SCHOOL,California Private High School,All,3.0,9,NaN
166379,F BRAVO MEDICAL MAGNET HS51719,San Diego,Los Angeles,Los Angeles,1999,F BRAVO MEDICAL MAGNET HS,California Public High School,White,3.0,6,NaN
...,...,...,...,...,...,...,...,...,...,...,...
587363,YORK MILLS COLLEGIATE INST826961,Los Angeles,NaN,CANADA,2016,YORK MILLS COLLEGIATE INST,Foreign Institution,All,NaN,5,NaN
587365,YUEZHOU HIGH SCHOOL694441,Universitywide,NaN,"CHINA, PEOPLES REPUBLIC",2015,YUEZHOU HIGH SCHOOL,Foreign Institution,Inter- national,NaN,9,NaN
587367,YUEZHOU HIGH SCHOOL694441,Irvine,NaN,"CHINA, PEOPLES REPUBLIC",2015,YUEZHOU HIGH SCHOOL,Foreign Institution,Inter- national,NaN,8,NaN
587372,ZAMA AMERICAN HIGH SCHOOL DOD561980,Universitywide,NaN,JAPAN,2013,ZAMA AMERICAN HIGH SCHOOL DOD,Foreign Institution,All,NaN,7,NaN
587374,ZAMA AMERICAN HIGH SCHOOL DOD561980,Universitywide,NaN,JAPAN,2013,ZAMA AMERICAN HIGH SCHOOL DOD,Foreign Institution,Asian,NaN,6,NaN
587376,ZHANGJIAGANG IVY EXPERIMENTAL694355,Berkeley,NaN,"CHINA, PEOPLES REPUBLIC",2015,ZHANGJIAGANG IVY EXPERIMENTAL,Foreign Institution,All,NaN,9,NaN
587377,ZHANGJIAGANG IVY EXPERIMENTAL694355,Berkeley,NaN,"CHINA, PEOPLES REPUBLIC",2016,ZHANGJIAGANG IVY EXPERIMENTAL,Foreign Institution,All,NaN,16,NaN
587407,ZHEJIANG JINHUA AIQING SCHOOL694480,Irvine,NaN,"CHINA, PEOPLES REPUBLIC",2016,ZHEJIANG JINHUA AIQING SCHOOL,Foreign Institution,All,NaN,5,NaN
587410,ZHENGZHOU FOREIGN LANGUAGE SCH694361,Universitywide,NaN,"CHINA, PEOPLES REPUBLIC",2012,ZHENGZHOU FOREIGN LANGUAGE SCH,Foreign Institution,Inter- national,NaN,30,NaN
587413,ZHENGZHOU FOREIGN LANGUAGE SCH694361,Berkeley,NaN,"CHINA, PEOPLES REPUBLIC",2014,ZHENGZHOU FOREIGN LANGUAGE SCH,Foreign Institution,Inter- national,NaN,27,NaN
587414,ZHENGZHOU FOREIGN LANGUAGE SCH694361,Berkeley,NaN,"CHINA, PEOPLES REPUBLIC",2016,ZHENGZHOU FOREIGN LANGUAGE SCH,Foreign Institution,Inter- national,NaN,46,NaN
587418,ZHENGZHOU FOREIGN LANGUAGE SCH694361,Irvine,NaN,"CHINA, PEOPLES REPUBLIC",2011,ZHENGZHOU FOREIGN LANGUAGE SCH,Foreign Institution,All,NaN,5,NaN
587424,ZHENGZHOU FOREIGN LANGUAGE SCH694361,Los Angeles,NaN,"CHINA, PEOPLES REPUBLIC",2014,ZHENGZHOU FOREIGN LANGUAGE SCH,Foreign Institution,All,NaN,38,NaN
587426,ZHENGZHOU FOREIGN LANGUAGE SCH694361,Los Angeles,NaN,"CHINA, PEOPLES REPUBLIC",2012,ZHENGZHOU FOREIGN LANGUAGE SCH,Foreign Institution,Inter- national,NaN,26,NaN
587427,ZHENGZHOU FOREIGN LANGUAGE SCH694361,Los Angeles,NaN,"CHINA, PEOPLES REPUBLIC",2014,ZHENGZHOU FOREIGN LANGUAGE SCH,Foreign Institution,Inter- national,NaN,36,NaN
587428,ZHENGZHOU FOREIGN LANGUAGE SCH694361,Los Angeles,NaN,"CHINA, PEOPLES REPUBLIC",2016,ZHENGZHOU FOREIGN LANGUAGE SCH,Foreign Institution,Inter- national,NaN,55,NaN
587441,ZHENGZHOU MIDDLE SCHOOL694448,Los Angeles,NaN,"CHINA, PEOPLES REPUBLIC",2013,ZHENGZHOU MIDDLE SCHOOL,Foreign Institution,All,NaN,6,NaN
587452,ZHENGZHOU NO 7 MIDDLE SCHOOL694440,Los Angeles,NaN,"CHINA, PEOPLES REPUBLIC",2015,ZHENGZHOU NO 7 MIDDLE SCHOOL,Foreign Institution,All,NaN,11,NaN
587453,ZHENGZHOU NO 7 MIDDLE SCHOOL694440,Los Angeles,NaN,"CHINA, PEOPLES REPUBLIC",2016,ZHENGZHOU NO 7 MIDDLE SCHOOL,Foreign Institution,All,NaN,14,NaN
587460,ZHENGZHOU NO 11 MIDDLE SCHOOL694432,San Diego,NaN,"CHINA, PEOPLES REPUBLIC",2016,ZHENGZHOU NO 11 MIDDLE SCHOOL,Foreign Institution,All,NaN,7,NaN
587464,ZHENGZHOU NO 47 MIDDLE & HIGH694388,Davis,NaN,"CHINA, PEOPLES REPUBLIC",2015,ZHENGZHOU NO 47 MIDDLE & HIGH,Foreign Institution,All,NaN,5,NaN
587466,ZHENGZHOU NO 47 MIDDLE & HIGH694388,Irvine,NaN,"CHINA, PEOPLES REPUBLIC",2016,ZHENGZHOU NO 47 MIDDLE & HIGH,Foreign Institution,All,NaN,5,NaN
587474,ZHENHAI HIGH SCH OF ZHEJIANG694294,Berkeley,NaN,"CHINA, PEOPLES REPUBLIC",2013,ZHENHAI HIGH SCH OF ZHEJIANG,Foreign Institution,All,NaN,22,NaN
587475,ZHENHAI HIGH SCH OF ZHEJIANG694294,Berkeley,NaN,"CHINA, PEOPLES REPUBLIC",2013,ZHENHAI HIGH SCH OF ZHEJIANG,Foreign Institution,Inter- national,NaN,21,NaN
587476,ZHENHAI HIGH SCH OF ZHEJIANG694294,Davis,NaN,"CHINA, PEOPLES REPUBLIC",2013,ZHENHAI HIGH SCH OF ZHEJIANG,Foreign Institution,Inter- national,NaN,19,NaN
587480,ZHENHAI HIGH SCH OF ZHEJIANG694294,Los Angeles,NaN,"CHINA, PEOPLES REPUBLIC",2016,ZHENHAI HIGH SCH OF ZHEJIANG,Foreign Institution,Inter- national,NaN,29,NaN
587484,ZHENHAI HIGH SCH OF ZHEJIANG694294,San Diego,NaN,"CHINA, PEOPLES REPUBLIC",2016,ZHENHAI HIGH SCH OF ZHEJIANG,Foreign Institution,Inter- national,NaN,39,NaN
587490,ZHUHAI NO 1 HIGH SCHOOL694565,Los Angeles,NaN,"CHINA, PEOPLES REPUBLIC",2015,ZHUHAI NO 1 HIGH SCHOOL,Foreign Institution,All,NaN,13,NaN
587493,ZIBO EXPERIMENTAL HIGH SCHOOL694601,Universitywide,NaN,"CHINA, PEOPLES REPUBLIC",2016,ZIBO EXPERIMENTAL HIGH SCHOOL,Foreign Institution,All,NaN,6,NaN
587499,ZURICH INTERNATIONAL SCHOOL796330,Los Angeles,NaN,SWITZERLAND,2017,ZURICH INTERNATIONAL SCHOOL,Foreign Institution,All,NaN,6,NaN

In [20]:
transfers.sort_values('adm (SUM)', ascending=False)

,Calculation1,Campus,City,County/State/ Territory,Fall Term,School,Sch Src TR,Uad Uc Ethn 6 Cat,adm (SUM),app (SUM),enr (SUM)
85454,SANTA MONICA COLLEGE4691,Universitywide,Santa Monica,Los Angeles,2017,SANTA MONICA COLLEGE,California Community Colleges (CCC),All,3328.0,4412,2578.0
85453,SANTA MONICA COLLEGE4691,Universitywide,Santa Monica,Los Angeles,2016,SANTA MONICA COLLEGE,California Community Colleges (CCC),All,3228.0,4570,2408.0
85450,SANTA MONICA COLLEGE4691,Universitywide,Santa Monica,Los Angeles,2010,SANTA MONICA COLLEGE,California Community Colleges (CCC),All,3127.0,4171,1983.0
58598,SANTA MONICA COLLEGE4691,Universitywide,Santa Monica,Los Angeles,2009,SANTA MONICA COLLEGE,California Community Colleges (CCC),All,3081.0,3949,2056.0
6966,SANTA MONICA COLLEGE4691,Universitywide,Santa Monica,Los Angeles,2015,SANTA MONICA COLLEGE,California Community Colleges (CCC),All,3046.0,4314,2217.0
8473,SANTA MONICA COLLEGE4691,Universitywide,Santa Monica,Los Angeles,2012,SANTA MONICA COLLEGE,California Community Colleges (CCC),All,2959.0,4222,2091.0
85451,SANTA MONICA COLLEGE4691,Universitywide,Santa Monica,Los Angeles,2011,SANTA MONICA COLLEGE,California Community Colleges (CCC),All,2944.0,4353,2109.0
14557,SANTA MONICA COLLEGE4691,Universitywide,Santa Monica,Los Angeles,2013,SANTA MONICA COLLEGE,California Community Colleges (CCC),All,2837.0,4053,2100.0
85452,SANTA MONICA COLLEGE4691,Universitywide,Santa Monica,Los Angeles,2014,SANTA MONICA COLLEGE,California Community Colleges (CCC),All,2817.0,4088,2159.0
85449,SANTA MONICA COLLEGE4691,Universitywide,Santa Monica,Los Angeles,2008,SANTA MONICA COLLEGE,California Community Colleges (CCC),All,2754.0,3400,1793.0
34326,SANTA MONICA COLLEGE4691,Universitywide,Santa Monica,Los Angeles,2006,SANTA MONICA COLLEGE,California Community Colleges (CCC),All,2686.0,3234,1912.0
85448,SANTA MONICA COLLEGE4691,Universitywide,Santa Monica,Los Angeles,2007,SANTA MONICA COLLEGE,California Community Colleges (CCC),All,2552.0,3126,1821.0
19048,SANTA MONICA COLLEGE4691,Universitywide,Snta Monica,Los Angeles,2004,SANTA MONICA COLLEGE,California Community Colleges (CCC),All,2536.0,3467,1904.0
32334,SANTA MONICA COLLEGE4691,Universitywide,Santa Monica,Los Angeles,2005,SANTA MONICA COLLEGE,California Community Colleges (CCC),All,2481.0,3184,1764.0
45835,DE ANZA COLLEGE4286,Universitywide,Cupertino,Santa Clara,2016,DE ANZA COLLEGE,California Community Colleges (CCC),All,2456.0,3267,1902.0
25373,DE ANZA COLLEGE4286,Universitywide,Cupertino,Santa Clara,2017,DE ANZA COLLEGE,California Community Colleges (CCC),All,2444.0,3112,1876.0
21237,SANTA MONICA COLLEGE4691,Universitywide,Santa Monica,Los Angeles,2003,SANTA MONICA COLLEGE,California Community Colleges (CCC),All,2331.0,3177,1744.0
47436,DIABLO VALLEY COLLEGE4295,Universitywide,Pleasant Hill,Contra Costa,2017,DIABLO VALLEY COLLEGE,California Community Colleges (CCC),All,2296.0,2748,1876.0
47433,DIABLO VALLEY COLLEGE4295,Universitywide,Pleasant Hill,Contra Costa,2016,DIABLO VALLEY COLLEGE,California Community Colleges (CCC),All,2283.0,2886,1842.0
65867,SANTA MONICA COLLEGE4691,Universitywide,Santa Monica,Los Angeles,2001,SANTA MONICA COLLEGE,California Community Colleges (CCC),All,2253.0,3065,1623.0
47110,SANTA MONICA COLLEGE4691,Universitywide,Santa Monica,Los Angeles,2002,SANTA MONICA COLLEGE,California Community Colleges (CCC),All,2197.0,3066,1559.0
9736,DE ANZA COLLEGE4286,Universitywide,Cupertino,Santa Clara,2011,DE ANZA COLLEGE,California Community Colleges (CCC),All,2134.0,2876,1596.0
45830,DE ANZA COLLEGE4286,Universitywide,Cupertino,Santa Clara,2014,DE ANZA COLLEGE,California Community Colleges (CCC),All,2101.0,2819,1615.0
47432,DIABLO VALLEY COLLEGE4295,Universitywide,Pleasant Hill,Contra Costa,2015,DIABLO VALLEY COLLEGE,California Community Colleges (CCC),All,2070.0,2783,1682.0
45834,DE ANZA COLLEGE4286,Universitywide,Cupertino,Santa Clara,2015,DE ANZA COLLEGE,California Community Colleges (CCC),All,2032.0,2898,1540.0
39877,PASADENA CITY COLLEGE4604,Universitywide,Pasadena,Los Angeles,2017,PASADENA CITY COLLEGE,California Community Colleges (CCC),All,2030.0,2604,1570.0
5683,DIABLO VALLEY COLLEGE4295,Universitywide,Pleasant Hill,Contra Costa,2014,DIABLO VALLEY COLLEGE,California Community Colleges (CCC),All,2022.0,2565,1656.0
21928,DE ANZA COLLEGE4286,Universitywide,Cupertino,Santa Clara,2010,DE ANZA COLLEGE,California Community Colleges (CCC),All,2018.0,2438,1380.0
45827,DE ANZA COLLEGE4286,Universitywide,Cupertino,Santa Clara,2013,DE ANZA COLLEGE,California Community Colleges (CCC),All,2006.0,2724,1491.0
42170,DE ANZA COLLEGE4286,Universitywide,Cupertino,Santa Clara,2009,DE ANZA COLLEGE,California Community Colleges (CCC),All,1917.0,2303,1326.0
...,...,...,...,...,...,...,...,...,...,...,...
103905,WASHINGTON990326,San Diego,NaN,Washington,2014,WASHINGTON,Non-California Institution (US),Inter- national,NaN,30,NaN
103908,WASHINGTON990326,San Diego,NaN,Washington,2017,WASHINGTON,Non-California Institution (US),Inter- national,NaN,36,NaN
103909,WASHTENAW COMMUNITY COLLEGE1935,Universitywide,Ann Arbor,Michigan,1999,WASHTENAW COMMUNITY COLLEGE,Non-California Institution (US),All,NaN,12,NaN
103911,WASHTENAW COMMUNITY COLLEGE1935,Berkeley,Ann Arbor,Michigan,2014,WASHTENAW COMMUNITY COLLEGE,Non-California Institution (US),All,NaN,10,NaN
103914,WESTERN WASHINGTON UNIVERSITY4947,Universitywide,Bellingham,Washington,1997,WESTERN WASHINGTON UNIVERSITY,Non-California Institution (US),All,NaN,10,NaN
103915,WESTERN WASHINGTON UNIVERSITY4947,Universitywide,Bellingham,Washington,1998,WESTERN WASHINGTON UNIVERSITY,Non-California Institution (US),All,NaN,18,NaN
103917,WESTERN WASHINGTON UNIVERSITY4947,Universitywide,Bellingham,Washington,2000,WESTERN WASHINGTON UNIVERSITY,Non-California Institution (US),All,NaN,12,NaN
103921,WESTERN WASHINGTON UNIVERSITY4947,Universitywide,Bellingham,Washington,2014,WESTERN WASHINGTON UNIVERSITY,Non-California Institution (US),All,NaN,10,NaN
103922,WESTERN WASHINGTON UNIVERSITY4947,Universitywide,Bellingham,Washington,1998,WESTERN WASHINGTON UNIVERSITY,Non-California Institution (US),White,NaN,12,NaN
103923,WESTERN WASHINGTON UNIVERSITY4947,Universitywide,Bellingham,Washington,1999,WESTERN WASHINGTON UNIVERSITY,Non-California Institution (US),White,NaN,10,NaN
103925,WESTRN MICHIGAN UNIVERSITY1902,Universitywide,Kalamazoo,Michigan,2006,WESTRN MICHIGAN UNIVERSITY,Non-California Institution (US),All,NaN,12,NaN
103926,WHATCOM CMTY COLLEGE1275,Universitywide,Bellingham,Washington,2001,WHATCOM CMTY COLLEGE,Non-California Institution (US),All,NaN,12,NaN
103931,WHATCOM CMTY COLLEGE1275,Berkeley,Bellingham,Washington,2014,WHATCOM CMTY COLLEGE,Non-California Institution (US),All,NaN,14,NaN
103933,WHATCOM CMTY COLLEGE1275,Berkeley,Bellingham,Washington,2014,WHATCOM CMTY COLLEGE,Non-California Institution (US),Inter- national,NaN,10,NaN
103934,WHATCOM CMTY COLLEGE1275,Berkeley,Bellingham,Washington,2015,WHATCOM CMTY COLLEGE,Non-California Institution (US),Inter- national,NaN,12,NaN
103935,WHATCOM CMTY COLLEGE1275,Berkeley,Bellingham,Washington,2017,WHATCOM CMTY COLLEGE,Non-California Institution (US),Inter- national,NaN,22,NaN
103938,WHATCOM CMTY COLLEGE1275,Los Angeles,Bellingham,Washington,2013,WHATCOM CMTY COLLEGE,Non-California Institution (US),All,NaN,10,NaN
103939,WHATCOM CMTY COLLEGE1275,Los Angeles,Bellingham,Washington,2015,WHATCOM CMTY COLLEGE,Non-California Institution (US),All,NaN,14,NaN
103941,WHATCOM CMTY COLLEGE1275,Los Angeles,Bellingham,Washington,2017,WHATCOM CMTY COLLEGE,Non-California Institution (US),All,NaN,44,NaN
103942,WHATCOM CMTY COLLEGE1275,Los Angeles,Bellingham,Washington,2015,WHATCOM CMTY COLLEGE,Non-California Institution (US),Inter- national,NaN,12,NaN
103946,WHATCOM CMTY COLLEGE1275,Santa Cruz,Bellingham,Washington,2017,WHATCOM CMTY COLLEGE,Non-California Institution (US),Inter- national,NaN,14,NaN
103949,WILLAMETTE UNIVERSITY4954,Universitywide,Salem,Oregon,1998,WILLAMETTE UNIVERSITY,Non-California Institution (US),All,NaN,10,NaN
103950,WILLAMETTE UNIVERSITY4954,Universitywide,Salem,Oregon,1999,WILLAMETTE UNIVERSITY,Non-California Institution (US),All,NaN,10,NaN
103955,WILLAMETTE UNIVERSITY4954,Davis,Salem,Oregon,2016,WILLAMETTE UNIVERSITY,Non-California Institution (US),All,NaN,10,NaN
103956,WILLIAM R HARPER COLLEGE1932,Universitywide,Palatine,Illinois,2001,WILLIAM R HARPER COLLEGE,Non-California Institution (US),All,NaN,16,NaN
103957,WILLIAM R HARPER COLLEGE1932,Universitywide,Palatine,Illinois,2005,WILLIAM R HARPER COLLEGE,Non-California Institution (US),All,NaN,14,NaN
103958,WISCONSIN990328,Universitywide,NaN,Wisconsin,2005,WISCONSIN,Non-California Institution (US),All,NaN,14,NaN
103959,WISCONSIN990328,Universitywide,NaN,Wisconsin,2015,WISCONSIN,Non-California Institution (US),All,NaN,5,NaN
103960,WISCONSIN990328,Universitywide,NaN,Wisconsin,2016,WISCONSIN,Non-California Institution (US),All,NaN,12,NaN
103961,WRIGHT STATE UNIVERSITY DAYTN1179,Universitywide,Dayton,Ohio,2013,WRIGHT STATE UNIVERSITY DAYTN,Non-California Institution (US),All,NaN,12,NaN

In [34]:
transfers.sort_values('Fall Term').head()

,Calculation1,Campus,City,County/State/ Territory,Fall Term,School,Sch Src TR,Uad Uc Ethn 6 Cat,adm (SUM),app (SUM),enr (SUM)
42873,RIO HONDO COLLEGE4663,Irvine,Whittier,Los Angeles,1994,RIO HONDO COLLEGE,California Community Colleges (CCC),All,56.0,80,20.0
24836,SAN JOAQUIN DELTA COLLEGE4706,Davis,Stockton,San Joaquin,1994,SAN JOAQUIN DELTA COLLEGE,California Community Colleges (CCC),White,64.0,88,44.0
48709,MOORPARK COLLEGE4512,Berkeley,Moorpark,Ventura,1994,MOORPARK COLLEGE,California Community Colleges (CCC),Hispanic/ Latino,NaN,14,NaN
98296,UC SANTA BARBARA4835,Berkeley,Santa Barbara,Santa Barbara,1994,UC SANTA BARBARA,University of California (UC),Hispanic/ Latino,NaN,16,NaN
84292,SANTA ANA COLLEGE4689,San Diego,Santa Ana,Orange,1994,SANTA ANA COLLEGE,California Community Colleges (CCC),Hispanic/ Latino,8.0,12,NaN

In [23]:
print(list(set(freshmen.loc[:,'Sch Src FR'])))

['Foreign Institution', 'California Private High School', 'California Public High School', 'Non-CA Domestic High School']

In [24]:
print(list(set(transfers.loc[:,'Sch Src TR'])))

['Other (not to include unknown)', 'Foreign Institution', 'Non-California Institution (US)', 'California Community Colleges (CCC)', 'University of California (UC)', 'CA Private Institutions', 'California State Universities (CSU)']

In [25]:
help = freshmen.loc[freshmen['Sch Src FR'] == 'California Public High School']
me = freshmen.loc[freshmen['Sch Src FR'] == 'California Private High School']

In [49]:
x = freshmen.groupby(["Campus"]).count().sort_values(by="adm (SUM)")
x

,Calculation1,City,County/State/ Territory,Fall Term,School,Sch Src FR,Uad Uc Ethn 6 Cat,adm (SUM),app (SUM),enr (SUM)
Campus,,,,,,,,,,
Merced,14817,14815,14817,14817,14817,14817,14817,14282,14817,2824
Berkeley,64776,61652,64776,64776,64776,64776,64776,36869,64776,17615
Riverside,39854,39700,39854,39854,39854,39854,39854,38187,39854,15034
Santa Cruz,43743,43339,43743,43743,43743,43743,43743,40707,43743,14265
Los Angeles,70722,67674,70722,70722,70722,70722,70722,42886,70722,21504
Irvine,53796,52423,53796,53796,53796,53796,53796,46520,53796,18307
San Diego,59838,57716,59838,59838,59838,59838,59838,47414,59838,17767
Davis,55516,54178,55516,55516,55516,55516,55516,48112,55516,19890
Santa Barbara,60023,59102,60023,60023,60023,60023,60023,51885,60023,19818
Universitywide,124416,117509,124416,124416,124416,124416,124416,116557,124416,83683

In [50]:
prop = x['adm (SUM)'] / x['app (SUM)']
prop

Campus
Merced            0.963893
Berkeley          0.569177
Riverside         0.958172
Santa Cruz        0.930595
Los Angeles       0.606403
Irvine            0.864748
San Diego         0.792373
Davis             0.866633
Santa Barbara     0.864419
Universitywide    0.936833
dtype: float64

In [53]:
gpa.groupby(["Campus"]).mean().sort_values(by="Adm GPA (SUM)")

                  Fall Term  Adm GPA (SUM)  App GPA (SUM)  Enrl GPA (SUM)
Campus
Merced          2011.006270       3.547102       3.423051        3.477554
Riverside       2007.188794       3.590100       3.446614        3.402879
Santa Cruz      2007.320350       3.675936       3.502721        3.478790
Universitywide  2007.916748       3.795111       3.673213        3.775328
Santa Barbara   2007.561768       3.841144       3.595907        3.658178
Irvine          2007.729670       3.882455       3.605246        3.723817
Davis           2007.580543       3.887820       3.647649        3.736864
San Diego       2007.802723       4.009340       3.702803        3.864250
Los Angeles     2008.139680       4.048286       3.736466        3.947703
Berkeley        2007.957256       4.077569       3.799817        3.981637

In [26]:
#How many high schools are included in all three of the datasets?
len(set(gpa['Calculation1']) & set(transfers['Calculation1']) & set(freshmen['Calculation1']))

34

In [27]:
#How many high schools are included in only 2 of the datasets? (gpa & transfers)
len(set(gpa['Calculation1']) & set(transfers['Calculation1']))

56

In [28]:
#How many high schools are included in only 2 of the datasets? (gpa & freshmen)
len(set(gpa['Calculation1']) & set(freshmen['Calculation1']))

2903

In [29]:
#How many high schools are included in only 2 of the datasets? (freshmen & transfers)
len(set(transfers['Calculation1']) & set(freshmen['Calculation1']))

35